/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonSize, ButtonType, ButtonVariant } from "./components/cap-button/cap-button";
import { InputType } from "./components/cap-input/cap-input";
import { TextareaResize } from "./components/cap-textarea/cap-textarea";
export { ButtonSize, ButtonType, ButtonVariant } from "./components/cap-button/cap-button";
export { InputType } from "./components/cap-input/cap-input";
export { TextareaResize } from "./components/cap-textarea/cap-textarea";
export namespace Components {
    interface CapButton {
        /**
          * Accessible label for icon-only buttons
         */
        "ariaLabel": string;
        /**
          * Disables the button
          * @default false
         */
        "disabled": boolean;
        /**
          * Stretches the button to full container width
          * @default false
         */
        "fullWidth": boolean;
        /**
          * Shows a loading spinner and disables interaction
          * @default false
         */
        "loading": boolean;
        /**
          * Size of the button
          * @default 'md'
         */
        "size": ButtonSize;
        /**
          * HTML button type
          * @default 'button'
         */
        "type": ButtonType;
        /**
          * Visual style of the button
          * @default 'primary'
         */
        "variant": ButtonVariant;
    }
    interface CapCheckbox {
        /**
          * Whether the checkbox is checked
          * @default false
         */
        "checked": boolean;
        /**
          * Disables the checkbox
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message
         */
        "error": string;
        /**
          * Hint text
         */
        "hint": string;
        /**
          * Indeterminate state — visually a dash, neither checked nor unchecked
          * @default false
         */
        "indeterminate": boolean;
        /**
          * Label text
         */
        "label": string;
        /**
          * Name attribute for form submission
         */
        "name": string;
        /**
          * Marks the checkbox as required
          * @default false
         */
        "required": boolean;
        /**
          * Value submitted with the form
         */
        "value": string;
    }
    interface CapInput {
        /**
          * Disables the input
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message — takes priority over hint and success
         */
        "error": string;
        /**
          * Hint text
         */
        "hint": string;
        /**
          * Label text
         */
        "label": string;
        /**
          * Input name for forms
         */
        "name": string;
        /**
          * Placeholder text
         */
        "placeholder": string;
        /**
          * Makes the input read-only
          * @default false
         */
        "readonly": boolean;
        /**
          * Marks the input as required
          * @default false
         */
        "required": boolean;
        /**
          * Success message — takes priority over hint
         */
        "success": string;
        /**
          * Input type
          * @default 'text'
         */
        "type": InputType;
        /**
          * Input value
          * @default ''
         */
        "value": string;
    }
    interface CapTextarea {
        /**
          * Accessible label for when no visible label is used
         */
        "ariaLabel": string;
        /**
          * Disables the textarea
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message — takes priority over hint and success
         */
        "error": string;
        /**
          * Hint text shown below the textarea
         */
        "hint": string;
        /**
          * Label text
         */
        "label": string;
        /**
          * Maximum number of characters allowed
         */
        "maxlength": number;
        /**
          * Name attribute for form submission
         */
        "name": string;
        /**
          * Placeholder text
         */
        "placeholder": string;
        /**
          * Makes the textarea read-only
          * @default false
         */
        "readonly": boolean;
        /**
          * Marks the textarea as required
          * @default false
         */
        "required": boolean;
        /**
          * Whether the textarea can be resized
          * @default 'vertical'
         */
        "resize": TextareaResize;
        /**
          * Number of visible rows
          * @default 4
         */
        "rows": number;
        /**
          * Success message — takes priority over hint
         */
        "success": string;
        /**
          * The current value of the textarea
          * @default ''
         */
        "value": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface CapButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapButtonElement;
}
export interface CapCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapCheckboxElement;
}
export interface CapInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapInputElement;
}
export interface CapTextareaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapTextareaElement;
}
declare global {
    interface HTMLCapButtonElementEventMap {
        "capClick": MouseEvent;
    }
    interface HTMLCapButtonElement extends Components.CapButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapButtonElementEventMap>(type: K, listener: (this: HTMLCapButtonElement, ev: CapButtonCustomEvent<HTMLCapButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapButtonElementEventMap>(type: K, listener: (this: HTMLCapButtonElement, ev: CapButtonCustomEvent<HTMLCapButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapButtonElement: {
        prototype: HTMLCapButtonElement;
        new (): HTMLCapButtonElement;
    };
    interface HTMLCapCheckboxElementEventMap {
        "capChange": boolean;
    }
    interface HTMLCapCheckboxElement extends Components.CapCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapCheckboxElementEventMap>(type: K, listener: (this: HTMLCapCheckboxElement, ev: CapCheckboxCustomEvent<HTMLCapCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapCheckboxElementEventMap>(type: K, listener: (this: HTMLCapCheckboxElement, ev: CapCheckboxCustomEvent<HTMLCapCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapCheckboxElement: {
        prototype: HTMLCapCheckboxElement;
        new (): HTMLCapCheckboxElement;
    };
    interface HTMLCapInputElementEventMap {
        "capChange": string;
        "capInput": string;
        "capFocus": FocusEvent;
        "capBlur": FocusEvent;
        "capClear": void;
    }
    interface HTMLCapInputElement extends Components.CapInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapInputElementEventMap>(type: K, listener: (this: HTMLCapInputElement, ev: CapInputCustomEvent<HTMLCapInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapInputElementEventMap>(type: K, listener: (this: HTMLCapInputElement, ev: CapInputCustomEvent<HTMLCapInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapInputElement: {
        prototype: HTMLCapInputElement;
        new (): HTMLCapInputElement;
    };
    interface HTMLCapTextareaElementEventMap {
        "capChange": string;
        "capInput": string;
        "capFocus": FocusEvent;
        "capBlur": FocusEvent;
    }
    interface HTMLCapTextareaElement extends Components.CapTextarea, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapTextareaElementEventMap>(type: K, listener: (this: HTMLCapTextareaElement, ev: CapTextareaCustomEvent<HTMLCapTextareaElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapTextareaElementEventMap>(type: K, listener: (this: HTMLCapTextareaElement, ev: CapTextareaCustomEvent<HTMLCapTextareaElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapTextareaElement: {
        prototype: HTMLCapTextareaElement;
        new (): HTMLCapTextareaElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cap-button": HTMLCapButtonElement;
        "cap-checkbox": HTMLCapCheckboxElement;
        "cap-input": HTMLCapInputElement;
        "cap-textarea": HTMLCapTextareaElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CapButton {
        /**
          * Accessible label for icon-only buttons
         */
        "ariaLabel"?: string;
        /**
          * Disables the button
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Stretches the button to full container width
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * Shows a loading spinner and disables interaction
          * @default false
         */
        "loading"?: boolean;
        /**
          * Emitted when the button is clicked
         */
        "onCapClick"?: (event: CapButtonCustomEvent<MouseEvent>) => void;
        /**
          * Size of the button
          * @default 'md'
         */
        "size"?: ButtonSize;
        /**
          * HTML button type
          * @default 'button'
         */
        "type"?: ButtonType;
        /**
          * Visual style of the button
          * @default 'primary'
         */
        "variant"?: ButtonVariant;
    }
    interface CapCheckbox {
        /**
          * Whether the checkbox is checked
          * @default false
         */
        "checked"?: boolean;
        /**
          * Disables the checkbox
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message
         */
        "error"?: string;
        /**
          * Hint text
         */
        "hint"?: string;
        /**
          * Indeterminate state — visually a dash, neither checked nor unchecked
          * @default false
         */
        "indeterminate"?: boolean;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Name attribute for form submission
         */
        "name"?: string;
        /**
          * Emitted when the checked state changes
         */
        "onCapChange"?: (event: CapCheckboxCustomEvent<boolean>) => void;
        /**
          * Marks the checkbox as required
          * @default false
         */
        "required"?: boolean;
        /**
          * Value submitted with the form
         */
        "value"?: string;
    }
    interface CapInput {
        /**
          * Disables the input
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message — takes priority over hint and success
         */
        "error"?: string;
        /**
          * Hint text
         */
        "hint"?: string;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Input name for forms
         */
        "name"?: string;
        /**
          * Emitted when the input loses focus
         */
        "onCapBlur"?: (event: CapInputCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the value changes
         */
        "onCapChange"?: (event: CapInputCustomEvent<string>) => void;
        /**
          * Emitted when the clear button is clicked (search type)
         */
        "onCapClear"?: (event: CapInputCustomEvent<void>) => void;
        /**
          * Emitted when the input is focused
         */
        "onCapFocus"?: (event: CapInputCustomEvent<FocusEvent>) => void;
        /**
          * Emitted on input (every keystroke)
         */
        "onCapInput"?: (event: CapInputCustomEvent<string>) => void;
        /**
          * Placeholder text
         */
        "placeholder"?: string;
        /**
          * Makes the input read-only
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Marks the input as required
          * @default false
         */
        "required"?: boolean;
        /**
          * Success message — takes priority over hint
         */
        "success"?: string;
        /**
          * Input type
          * @default 'text'
         */
        "type"?: InputType;
        /**
          * Input value
          * @default ''
         */
        "value"?: string;
    }
    interface CapTextarea {
        /**
          * Accessible label for when no visible label is used
         */
        "ariaLabel"?: string;
        /**
          * Disables the textarea
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message — takes priority over hint and success
         */
        "error"?: string;
        /**
          * Hint text shown below the textarea
         */
        "hint"?: string;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Maximum number of characters allowed
         */
        "maxlength"?: number;
        /**
          * Name attribute for form submission
         */
        "name"?: string;
        /**
          * Emitted when the textarea loses focus
         */
        "onCapBlur"?: (event: CapTextareaCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the value changes (on blur)
         */
        "onCapChange"?: (event: CapTextareaCustomEvent<string>) => void;
        /**
          * Emitted when the textarea is focused
         */
        "onCapFocus"?: (event: CapTextareaCustomEvent<FocusEvent>) => void;
        /**
          * Emitted on every keystroke
         */
        "onCapInput"?: (event: CapTextareaCustomEvent<string>) => void;
        /**
          * Placeholder text
         */
        "placeholder"?: string;
        /**
          * Makes the textarea read-only
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Marks the textarea as required
          * @default false
         */
        "required"?: boolean;
        /**
          * Whether the textarea can be resized
          * @default 'vertical'
         */
        "resize"?: TextareaResize;
        /**
          * Number of visible rows
          * @default 4
         */
        "rows"?: number;
        /**
          * Success message — takes priority over hint
         */
        "success"?: string;
        /**
          * The current value of the textarea
          * @default ''
         */
        "value"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }

    interface CapButtonAttributes {
        "variant": ButtonVariant;
        "size": ButtonSize;
        "type": ButtonType;
        "disabled": boolean;
        "loading": boolean;
        "fullWidth": boolean;
        "ariaLabel": string;
    }
    interface CapCheckboxAttributes {
        "checked": boolean;
        "indeterminate": boolean;
        "disabled": boolean;
        "required": boolean;
        "name": string;
        "value": string;
        "label": string;
        "hint": string;
        "error": string;
    }
    interface CapInputAttributes {
        "type": InputType;
        "value": string;
        "name": string;
        "placeholder": string;
        "label": string;
        "hint": string;
        "error": string;
        "success": string;
        "disabled": boolean;
        "readonly": boolean;
        "required": boolean;
    }
    interface CapTextareaAttributes {
        "value": string;
        "name": string;
        "placeholder": string;
        "label": string;
        "hint": string;
        "error": string;
        "success": string;
        "rows": number;
        "resize": TextareaResize;
        "maxlength": number;
        "disabled": boolean;
        "readonly": boolean;
        "required": boolean;
        "ariaLabel": string;
    }
    interface MyComponentAttributes {
        "first": string;
        "middle": string;
        "last": string;
    }

    interface IntrinsicElements {
        "cap-button": Omit<CapButton, keyof CapButtonAttributes> & { [K in keyof CapButton & keyof CapButtonAttributes]?: CapButton[K] } & { [K in keyof CapButton & keyof CapButtonAttributes as `attr:${K}`]?: CapButtonAttributes[K] } & { [K in keyof CapButton & keyof CapButtonAttributes as `prop:${K}`]?: CapButton[K] };
        "cap-checkbox": Omit<CapCheckbox, keyof CapCheckboxAttributes> & { [K in keyof CapCheckbox & keyof CapCheckboxAttributes]?: CapCheckbox[K] } & { [K in keyof CapCheckbox & keyof CapCheckboxAttributes as `attr:${K}`]?: CapCheckboxAttributes[K] } & { [K in keyof CapCheckbox & keyof CapCheckboxAttributes as `prop:${K}`]?: CapCheckbox[K] };
        "cap-input": Omit<CapInput, keyof CapInputAttributes> & { [K in keyof CapInput & keyof CapInputAttributes]?: CapInput[K] } & { [K in keyof CapInput & keyof CapInputAttributes as `attr:${K}`]?: CapInputAttributes[K] } & { [K in keyof CapInput & keyof CapInputAttributes as `prop:${K}`]?: CapInput[K] };
        "cap-textarea": Omit<CapTextarea, keyof CapTextareaAttributes> & { [K in keyof CapTextarea & keyof CapTextareaAttributes]?: CapTextarea[K] } & { [K in keyof CapTextarea & keyof CapTextareaAttributes as `attr:${K}`]?: CapTextareaAttributes[K] } & { [K in keyof CapTextarea & keyof CapTextareaAttributes as `prop:${K}`]?: CapTextarea[K] };
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cap-button": LocalJSX.IntrinsicElements["cap-button"] & JSXBase.HTMLAttributes<HTMLCapButtonElement>;
            "cap-checkbox": LocalJSX.IntrinsicElements["cap-checkbox"] & JSXBase.HTMLAttributes<HTMLCapCheckboxElement>;
            "cap-input": LocalJSX.IntrinsicElements["cap-input"] & JSXBase.HTMLAttributes<HTMLCapInputElement>;
            "cap-textarea": LocalJSX.IntrinsicElements["cap-textarea"] & JSXBase.HTMLAttributes<HTMLCapTextareaElement>;
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
