/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonSize, ButtonType, ButtonVariant } from "./components/cap-button/cap-button";
import { ComboboxOption } from "./components/cap-combobox/cap-combobox";
import { MenuItem } from "./components/cap-dropdown-menu/cap-dropdown-menu";
import { InputType } from "./components/cap-input/cap-input";
import { MultiselectOption, MultiselectOverflow } from "./components/cap-multiselect/cap-multiselect";
import { SelectOption } from "./components/cap-select/cap-select";
import { TagInputOption } from "./components/cap-tag-input/cap-tag-input";
import { TextareaResize } from "./components/cap-textarea/cap-textarea";
export { ButtonSize, ButtonType, ButtonVariant } from "./components/cap-button/cap-button";
export { ComboboxOption } from "./components/cap-combobox/cap-combobox";
export { MenuItem } from "./components/cap-dropdown-menu/cap-dropdown-menu";
export { InputType } from "./components/cap-input/cap-input";
export { MultiselectOption, MultiselectOverflow } from "./components/cap-multiselect/cap-multiselect";
export { SelectOption } from "./components/cap-select/cap-select";
export { TagInputOption } from "./components/cap-tag-input/cap-tag-input";
export { TextareaResize } from "./components/cap-textarea/cap-textarea";
export namespace Components {
    interface CapButton {
        /**
          * Accessible label for icon-only buttons
         */
        "ariaLabel": string;
        /**
          * Disables the button
          * @default false
         */
        "disabled": boolean;
        /**
          * Stretches the button to full container width
          * @default false
         */
        "fullWidth": boolean;
        /**
          * Shows a loading spinner and disables interaction
          * @default false
         */
        "loading": boolean;
        /**
          * Size of the button
          * @default 'md'
         */
        "size": ButtonSize;
        /**
          * HTML button type
          * @default 'button'
         */
        "type": ButtonType;
        /**
          * Visual style of the button
          * @default 'primary'
         */
        "variant": ButtonVariant;
    }
    interface CapCheckbox {
        /**
          * Whether the checkbox is checked
          * @default false
         */
        "checked": boolean;
        /**
          * Disables the checkbox
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message
         */
        "error": string;
        /**
          * Hint text
         */
        "hint": string;
        /**
          * Indeterminate state — visually a dash, neither checked nor unchecked
          * @default false
         */
        "indeterminate": boolean;
        /**
          * Label text
         */
        "label": string;
        /**
          * Name attribute for form submission
         */
        "name": string;
        /**
          * Marks the checkbox as required
          * @default false
         */
        "required": boolean;
        /**
          * Value submitted with the form
         */
        "value": string;
    }
    interface CapCombobox {
        /**
          * Forces the dropdown open — useful for debugging styles
          * @default false
         */
        "defaultOpen": boolean;
        /**
          * Disables the combobox
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message
         */
        "error": string;
        /**
          * When true, typed text that doesn't match any option is accepted as a valid value. When false (default), blurring without selecting reverts the input to the last valid selection.
          * @default false
         */
        "freeText": boolean;
        /**
          * Hint text
         */
        "hint": string;
        /**
          * Label text
         */
        "label": string;
        /**
          * Name attribute for form submission
         */
        "name": string;
        /**
          * Array of options to filter and display
          * @default []
         */
        "options": ComboboxOption[];
        /**
          * Placeholder shown when input is empty
         */
        "placeholder": string;
        /**
          * Marks the combobox as required
          * @default false
         */
        "required": boolean;
        /**
          * Committed value — option.value when selected, or typed text when freeText=true
          * @default ''
         */
        "value": string;
    }
    interface CapDropdownMenu {
        /**
          * Horizontal alignment of the menu panel relative to the trigger
          * @default 'start'
         */
        "align": 'start' | 'end';
        /**
          * Disables the trigger
          * @default false
         */
        "disabled": boolean;
        /**
          * Optional icon shown in the trigger
         */
        "icon": string;
        /**
          * Menu items
          * @default []
         */
        "items": MenuItem[];
        /**
          * Trigger button label
          * @default ''
         */
        "label": string;
    }
    interface CapInput {
        /**
          * Disables the input
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message — takes priority over hint and success
         */
        "error": string;
        /**
          * Hint text
         */
        "hint": string;
        /**
          * Label text
         */
        "label": string;
        /**
          * Input name for forms
         */
        "name": string;
        /**
          * Placeholder text
         */
        "placeholder": string;
        /**
          * Makes the input read-only
          * @default false
         */
        "readonly": boolean;
        /**
          * Marks the input as required
          * @default false
         */
        "required": boolean;
        /**
          * Success message — takes priority over hint
         */
        "success": string;
        /**
          * Input type
          * @default 'text'
         */
        "type": InputType;
        /**
          * Input value
          * @default ''
         */
        "value": string;
    }
    interface CapMultiselect {
        /**
          * Forces the dropdown open — useful for debugging styles
          * @default false
         */
        "defaultOpen": boolean;
        /**
          * Disables the component
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message
         */
        "error": string;
        /**
          * When true, a text input is shown inside the trigger for filtering options. When false (default), the trigger is a select-only control.
          * @default false
         */
        "filterable": boolean;
        /**
          * Hint text
         */
        "hint": string;
        /**
          * Label text
         */
        "label": string;
        /**
          * Maximum chips shown in the trigger before a "+N" badge appears. Only relevant when overflow="single-line".
          * @default 3
         */
        "maxVisibleChips": number;
        /**
          * Name attribute for form submission
         */
        "name": string;
        /**
          * Array of options to display
          * @default []
         */
        "options": MultiselectOption[];
        /**
          * Controls chip layout. grow (default): the trigger expands vertically as chips are added. single-line: trigger stays one line; excess chips collapse into a "+N" badge.
          * @default 'grow'
         */
        "overflow": MultiselectOverflow;
        /**
          * Placeholder shown when no value is selected
         */
        "placeholder": string;
        /**
          * Marks the component as required
          * @default false
         */
        "required": boolean;
        /**
          * Currently selected values
          * @default []
         */
        "value": string[];
    }
    interface CapRadio {
        /**
          * Whether this radio is selected
          * @default false
         */
        "checked": boolean;
        /**
          * Disables the radio
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message
         */
        "error": string;
        /**
          * Hint text
         */
        "hint": string;
        /**
          * Label text
         */
        "label": string;
        /**
          * Name attribute — shared across radios in the same group
         */
        "name": string;
        /**
          * Marks the radio as required
          * @default false
         */
        "required": boolean;
        /**
          * Value submitted with the form
         */
        "value": string;
    }
    interface CapRadioGroup {
        /**
          * Disables all child radios
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message
         */
        "error": string;
        /**
          * Hint text
         */
        "hint": string;
        /**
          * Group label
         */
        "label": string;
        /**
          * Name shared across all child cap-radio elements
         */
        "name": string;
        /**
          * Marks all child radios as required
          * @default false
         */
        "required": boolean;
        /**
          * Currently selected value
         */
        "value": string;
    }
    interface CapSelect {
        /**
          * Disables the select
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message
         */
        "error": string;
        /**
          * Hint text
         */
        "hint": string;
        /**
          * Label text
         */
        "label": string;
        /**
          * Name attribute for form submission
         */
        "name": string;
        /**
          * Array of options to render
          * @default []
         */
        "options": SelectOption[];
        /**
          * Placeholder shown when no value is selected
         */
        "placeholder": string;
        /**
          * Marks the select as required
          * @default false
         */
        "required": boolean;
        /**
          * Currently selected value
          * @default ''
         */
        "value": string;
    }
    interface CapTagInput {
        /**
          * Forces the dropdown open — useful for debugging styles
          * @default false
         */
        "defaultOpen": boolean;
        /**
          * Disables the component
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message
         */
        "error": string;
        /**
          * Hint text
         */
        "hint": string;
        /**
          * Label text
         */
        "label": string;
        /**
          * Name attribute for form submission
         */
        "name": string;
        /**
          * Optional list of suggestions shown as an autocomplete dropdown while typing. If omitted, the component operates as a pure free-text tag input.
          * @default []
         */
        "options": TagInputOption[];
        /**
          * Placeholder shown when input is empty and no tags are present
         */
        "placeholder": string;
        /**
          * Marks the component as required
          * @default false
         */
        "required": boolean;
        /**
          * Current tags. When a suggestion is selected, stores the option's value. When typed freely, stores the raw text.
          * @default []
         */
        "value": string[];
    }
    interface CapTextarea {
        /**
          * Accessible label for when no visible label is used
         */
        "ariaLabel": string;
        /**
          * Disables the textarea
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message — takes priority over hint and success
         */
        "error": string;
        /**
          * Hint text shown below the textarea
         */
        "hint": string;
        /**
          * Label text
         */
        "label": string;
        /**
          * Maximum number of characters allowed
         */
        "maxlength": number;
        /**
          * Name attribute for form submission
         */
        "name": string;
        /**
          * Placeholder text
         */
        "placeholder": string;
        /**
          * Makes the textarea read-only
          * @default false
         */
        "readonly": boolean;
        /**
          * Marks the textarea as required
          * @default false
         */
        "required": boolean;
        /**
          * Whether the textarea can be resized
          * @default 'vertical'
         */
        "resize": TextareaResize;
        /**
          * Number of visible rows
          * @default 4
         */
        "rows": number;
        /**
          * Success message — takes priority over hint
         */
        "success": string;
        /**
          * The current value of the textarea
          * @default ''
         */
        "value": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface CapButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapButtonElement;
}
export interface CapCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapCheckboxElement;
}
export interface CapComboboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapComboboxElement;
}
export interface CapDropdownMenuCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapDropdownMenuElement;
}
export interface CapInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapInputElement;
}
export interface CapMultiselectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapMultiselectElement;
}
export interface CapRadioCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapRadioElement;
}
export interface CapRadioGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapRadioGroupElement;
}
export interface CapSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapSelectElement;
}
export interface CapTagInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapTagInputElement;
}
export interface CapTextareaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapTextareaElement;
}
declare global {
    interface HTMLCapButtonElementEventMap {
        "capClick": MouseEvent;
    }
    interface HTMLCapButtonElement extends Components.CapButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapButtonElementEventMap>(type: K, listener: (this: HTMLCapButtonElement, ev: CapButtonCustomEvent<HTMLCapButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapButtonElementEventMap>(type: K, listener: (this: HTMLCapButtonElement, ev: CapButtonCustomEvent<HTMLCapButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapButtonElement: {
        prototype: HTMLCapButtonElement;
        new (): HTMLCapButtonElement;
    };
    interface HTMLCapCheckboxElementEventMap {
        "capChange": boolean;
    }
    interface HTMLCapCheckboxElement extends Components.CapCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapCheckboxElementEventMap>(type: K, listener: (this: HTMLCapCheckboxElement, ev: CapCheckboxCustomEvent<HTMLCapCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapCheckboxElementEventMap>(type: K, listener: (this: HTMLCapCheckboxElement, ev: CapCheckboxCustomEvent<HTMLCapCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapCheckboxElement: {
        prototype: HTMLCapCheckboxElement;
        new (): HTMLCapCheckboxElement;
    };
    interface HTMLCapComboboxElementEventMap {
        "capChange": string;
        "capInput": string;
        "capFocus": FocusEvent;
        "capBlur": FocusEvent;
    }
    interface HTMLCapComboboxElement extends Components.CapCombobox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapComboboxElementEventMap>(type: K, listener: (this: HTMLCapComboboxElement, ev: CapComboboxCustomEvent<HTMLCapComboboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapComboboxElementEventMap>(type: K, listener: (this: HTMLCapComboboxElement, ev: CapComboboxCustomEvent<HTMLCapComboboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapComboboxElement: {
        prototype: HTMLCapComboboxElement;
        new (): HTMLCapComboboxElement;
    };
    interface HTMLCapDropdownMenuElementEventMap {
        "capSelect": MenuItem;
        "capToggle": { item: MenuItem; checked: boolean };
    }
    interface HTMLCapDropdownMenuElement extends Components.CapDropdownMenu, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapDropdownMenuElementEventMap>(type: K, listener: (this: HTMLCapDropdownMenuElement, ev: CapDropdownMenuCustomEvent<HTMLCapDropdownMenuElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapDropdownMenuElementEventMap>(type: K, listener: (this: HTMLCapDropdownMenuElement, ev: CapDropdownMenuCustomEvent<HTMLCapDropdownMenuElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapDropdownMenuElement: {
        prototype: HTMLCapDropdownMenuElement;
        new (): HTMLCapDropdownMenuElement;
    };
    interface HTMLCapInputElementEventMap {
        "capChange": string;
        "capInput": string;
        "capFocus": FocusEvent;
        "capBlur": FocusEvent;
        "capClear": void;
    }
    interface HTMLCapInputElement extends Components.CapInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapInputElementEventMap>(type: K, listener: (this: HTMLCapInputElement, ev: CapInputCustomEvent<HTMLCapInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapInputElementEventMap>(type: K, listener: (this: HTMLCapInputElement, ev: CapInputCustomEvent<HTMLCapInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapInputElement: {
        prototype: HTMLCapInputElement;
        new (): HTMLCapInputElement;
    };
    interface HTMLCapMultiselectElementEventMap {
        "capChange": string[];
        "capInput": string;
        "capFocus": FocusEvent;
        "capBlur": FocusEvent;
    }
    interface HTMLCapMultiselectElement extends Components.CapMultiselect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapMultiselectElementEventMap>(type: K, listener: (this: HTMLCapMultiselectElement, ev: CapMultiselectCustomEvent<HTMLCapMultiselectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapMultiselectElementEventMap>(type: K, listener: (this: HTMLCapMultiselectElement, ev: CapMultiselectCustomEvent<HTMLCapMultiselectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapMultiselectElement: {
        prototype: HTMLCapMultiselectElement;
        new (): HTMLCapMultiselectElement;
    };
    interface HTMLCapRadioElementEventMap {
        "capChange": string;
    }
    interface HTMLCapRadioElement extends Components.CapRadio, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapRadioElementEventMap>(type: K, listener: (this: HTMLCapRadioElement, ev: CapRadioCustomEvent<HTMLCapRadioElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapRadioElementEventMap>(type: K, listener: (this: HTMLCapRadioElement, ev: CapRadioCustomEvent<HTMLCapRadioElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapRadioElement: {
        prototype: HTMLCapRadioElement;
        new (): HTMLCapRadioElement;
    };
    interface HTMLCapRadioGroupElementEventMap {
        "capChange": string;
    }
    interface HTMLCapRadioGroupElement extends Components.CapRadioGroup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapRadioGroupElementEventMap>(type: K, listener: (this: HTMLCapRadioGroupElement, ev: CapRadioGroupCustomEvent<HTMLCapRadioGroupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapRadioGroupElementEventMap>(type: K, listener: (this: HTMLCapRadioGroupElement, ev: CapRadioGroupCustomEvent<HTMLCapRadioGroupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapRadioGroupElement: {
        prototype: HTMLCapRadioGroupElement;
        new (): HTMLCapRadioGroupElement;
    };
    interface HTMLCapSelectElementEventMap {
        "capChange": string;
        "capFocus": FocusEvent;
        "capBlur": FocusEvent;
    }
    interface HTMLCapSelectElement extends Components.CapSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapSelectElementEventMap>(type: K, listener: (this: HTMLCapSelectElement, ev: CapSelectCustomEvent<HTMLCapSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapSelectElementEventMap>(type: K, listener: (this: HTMLCapSelectElement, ev: CapSelectCustomEvent<HTMLCapSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapSelectElement: {
        prototype: HTMLCapSelectElement;
        new (): HTMLCapSelectElement;
    };
    interface HTMLCapTagInputElementEventMap {
        "capChange": string[];
        "capInput": string;
        "capFocus": FocusEvent;
        "capBlur": FocusEvent;
    }
    interface HTMLCapTagInputElement extends Components.CapTagInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapTagInputElementEventMap>(type: K, listener: (this: HTMLCapTagInputElement, ev: CapTagInputCustomEvent<HTMLCapTagInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapTagInputElementEventMap>(type: K, listener: (this: HTMLCapTagInputElement, ev: CapTagInputCustomEvent<HTMLCapTagInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapTagInputElement: {
        prototype: HTMLCapTagInputElement;
        new (): HTMLCapTagInputElement;
    };
    interface HTMLCapTextareaElementEventMap {
        "capChange": string;
        "capInput": string;
        "capFocus": FocusEvent;
        "capBlur": FocusEvent;
    }
    interface HTMLCapTextareaElement extends Components.CapTextarea, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapTextareaElementEventMap>(type: K, listener: (this: HTMLCapTextareaElement, ev: CapTextareaCustomEvent<HTMLCapTextareaElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapTextareaElementEventMap>(type: K, listener: (this: HTMLCapTextareaElement, ev: CapTextareaCustomEvent<HTMLCapTextareaElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapTextareaElement: {
        prototype: HTMLCapTextareaElement;
        new (): HTMLCapTextareaElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cap-button": HTMLCapButtonElement;
        "cap-checkbox": HTMLCapCheckboxElement;
        "cap-combobox": HTMLCapComboboxElement;
        "cap-dropdown-menu": HTMLCapDropdownMenuElement;
        "cap-input": HTMLCapInputElement;
        "cap-multiselect": HTMLCapMultiselectElement;
        "cap-radio": HTMLCapRadioElement;
        "cap-radio-group": HTMLCapRadioGroupElement;
        "cap-select": HTMLCapSelectElement;
        "cap-tag-input": HTMLCapTagInputElement;
        "cap-textarea": HTMLCapTextareaElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CapButton {
        /**
          * Accessible label for icon-only buttons
         */
        "ariaLabel"?: string;
        /**
          * Disables the button
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Stretches the button to full container width
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * Shows a loading spinner and disables interaction
          * @default false
         */
        "loading"?: boolean;
        /**
          * Emitted when the button is clicked
         */
        "onCapClick"?: (event: CapButtonCustomEvent<MouseEvent>) => void;
        /**
          * Size of the button
          * @default 'md'
         */
        "size"?: ButtonSize;
        /**
          * HTML button type
          * @default 'button'
         */
        "type"?: ButtonType;
        /**
          * Visual style of the button
          * @default 'primary'
         */
        "variant"?: ButtonVariant;
    }
    interface CapCheckbox {
        /**
          * Whether the checkbox is checked
          * @default false
         */
        "checked"?: boolean;
        /**
          * Disables the checkbox
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message
         */
        "error"?: string;
        /**
          * Hint text
         */
        "hint"?: string;
        /**
          * Indeterminate state — visually a dash, neither checked nor unchecked
          * @default false
         */
        "indeterminate"?: boolean;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Name attribute for form submission
         */
        "name"?: string;
        /**
          * Emitted when the checked state changes
         */
        "onCapChange"?: (event: CapCheckboxCustomEvent<boolean>) => void;
        /**
          * Marks the checkbox as required
          * @default false
         */
        "required"?: boolean;
        /**
          * Value submitted with the form
         */
        "value"?: string;
    }
    interface CapCombobox {
        /**
          * Forces the dropdown open — useful for debugging styles
          * @default false
         */
        "defaultOpen"?: boolean;
        /**
          * Disables the combobox
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message
         */
        "error"?: string;
        /**
          * When true, typed text that doesn't match any option is accepted as a valid value. When false (default), blurring without selecting reverts the input to the last valid selection.
          * @default false
         */
        "freeText"?: boolean;
        /**
          * Hint text
         */
        "hint"?: string;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Name attribute for form submission
         */
        "name"?: string;
        /**
          * Emitted when focus leaves the component
         */
        "onCapBlur"?: (event: CapComboboxCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the committed value changes
         */
        "onCapChange"?: (event: CapComboboxCustomEvent<string>) => void;
        /**
          * Emitted when the input is focused
         */
        "onCapFocus"?: (event: CapComboboxCustomEvent<FocusEvent>) => void;
        /**
          * Emitted on every keystroke
         */
        "onCapInput"?: (event: CapComboboxCustomEvent<string>) => void;
        /**
          * Array of options to filter and display
          * @default []
         */
        "options"?: ComboboxOption[];
        /**
          * Placeholder shown when input is empty
         */
        "placeholder"?: string;
        /**
          * Marks the combobox as required
          * @default false
         */
        "required"?: boolean;
        /**
          * Committed value — option.value when selected, or typed text when freeText=true
          * @default ''
         */
        "value"?: string;
    }
    interface CapDropdownMenu {
        /**
          * Horizontal alignment of the menu panel relative to the trigger
          * @default 'start'
         */
        "align"?: 'start' | 'end';
        /**
          * Disables the trigger
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Optional icon shown in the trigger
         */
        "icon"?: string;
        /**
          * Menu items
          * @default []
         */
        "items"?: MenuItem[];
        /**
          * Trigger button label
          * @default ''
         */
        "label"?: string;
        /**
          * Emitted when an action or link item is activated
         */
        "onCapSelect"?: (event: CapDropdownMenuCustomEvent<MenuItem>) => void;
        /**
          * Emitted when a toggle item is activated; checked reflects the new state
         */
        "onCapToggle"?: (event: CapDropdownMenuCustomEvent<{ item: MenuItem; checked: boolean }>) => void;
    }
    interface CapInput {
        /**
          * Disables the input
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message — takes priority over hint and success
         */
        "error"?: string;
        /**
          * Hint text
         */
        "hint"?: string;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Input name for forms
         */
        "name"?: string;
        /**
          * Emitted when the input loses focus
         */
        "onCapBlur"?: (event: CapInputCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the value changes
         */
        "onCapChange"?: (event: CapInputCustomEvent<string>) => void;
        /**
          * Emitted when the clear button is clicked (search type)
         */
        "onCapClear"?: (event: CapInputCustomEvent<void>) => void;
        /**
          * Emitted when the input is focused
         */
        "onCapFocus"?: (event: CapInputCustomEvent<FocusEvent>) => void;
        /**
          * Emitted on input (every keystroke)
         */
        "onCapInput"?: (event: CapInputCustomEvent<string>) => void;
        /**
          * Placeholder text
         */
        "placeholder"?: string;
        /**
          * Makes the input read-only
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Marks the input as required
          * @default false
         */
        "required"?: boolean;
        /**
          * Success message — takes priority over hint
         */
        "success"?: string;
        /**
          * Input type
          * @default 'text'
         */
        "type"?: InputType;
        /**
          * Input value
          * @default ''
         */
        "value"?: string;
    }
    interface CapMultiselect {
        /**
          * Forces the dropdown open — useful for debugging styles
          * @default false
         */
        "defaultOpen"?: boolean;
        /**
          * Disables the component
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message
         */
        "error"?: string;
        /**
          * When true, a text input is shown inside the trigger for filtering options. When false (default), the trigger is a select-only control.
          * @default false
         */
        "filterable"?: boolean;
        /**
          * Hint text
         */
        "hint"?: string;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Maximum chips shown in the trigger before a "+N" badge appears. Only relevant when overflow="single-line".
          * @default 3
         */
        "maxVisibleChips"?: number;
        /**
          * Name attribute for form submission
         */
        "name"?: string;
        /**
          * Emitted when focus leaves the component
         */
        "onCapBlur"?: (event: CapMultiselectCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the selected values change
         */
        "onCapChange"?: (event: CapMultiselectCustomEvent<string[]>) => void;
        /**
          * Emitted when the trigger is focused
         */
        "onCapFocus"?: (event: CapMultiselectCustomEvent<FocusEvent>) => void;
        /**
          * Emitted on every keystroke in filterable mode
         */
        "onCapInput"?: (event: CapMultiselectCustomEvent<string>) => void;
        /**
          * Array of options to display
          * @default []
         */
        "options"?: MultiselectOption[];
        /**
          * Controls chip layout. grow (default): the trigger expands vertically as chips are added. single-line: trigger stays one line; excess chips collapse into a "+N" badge.
          * @default 'grow'
         */
        "overflow"?: MultiselectOverflow;
        /**
          * Placeholder shown when no value is selected
         */
        "placeholder"?: string;
        /**
          * Marks the component as required
          * @default false
         */
        "required"?: boolean;
        /**
          * Currently selected values
          * @default []
         */
        "value"?: string[];
    }
    interface CapRadio {
        /**
          * Whether this radio is selected
          * @default false
         */
        "checked"?: boolean;
        /**
          * Disables the radio
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message
         */
        "error"?: string;
        /**
          * Hint text
         */
        "hint"?: string;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Name attribute — shared across radios in the same group
         */
        "name"?: string;
        /**
          * Emitted when this radio is selected
         */
        "onCapChange"?: (event: CapRadioCustomEvent<string>) => void;
        /**
          * Marks the radio as required
          * @default false
         */
        "required"?: boolean;
        /**
          * Value submitted with the form
         */
        "value"?: string;
    }
    interface CapRadioGroup {
        /**
          * Disables all child radios
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message
         */
        "error"?: string;
        /**
          * Hint text
         */
        "hint"?: string;
        /**
          * Group label
         */
        "label"?: string;
        /**
          * Name shared across all child cap-radio elements
         */
        "name"?: string;
        /**
          * Emitted when the selected value changes
         */
        "onCapChange"?: (event: CapRadioGroupCustomEvent<string>) => void;
        /**
          * Marks all child radios as required
          * @default false
         */
        "required"?: boolean;
        /**
          * Currently selected value
         */
        "value"?: string;
    }
    interface CapSelect {
        /**
          * Disables the select
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message
         */
        "error"?: string;
        /**
          * Hint text
         */
        "hint"?: string;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Name attribute for form submission
         */
        "name"?: string;
        /**
          * Emitted when focus leaves the component
         */
        "onCapBlur"?: (event: CapSelectCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the selected value changes
         */
        "onCapChange"?: (event: CapSelectCustomEvent<string>) => void;
        /**
          * Emitted when the trigger is focused
         */
        "onCapFocus"?: (event: CapSelectCustomEvent<FocusEvent>) => void;
        /**
          * Array of options to render
          * @default []
         */
        "options"?: SelectOption[];
        /**
          * Placeholder shown when no value is selected
         */
        "placeholder"?: string;
        /**
          * Marks the select as required
          * @default false
         */
        "required"?: boolean;
        /**
          * Currently selected value
          * @default ''
         */
        "value"?: string;
    }
    interface CapTagInput {
        /**
          * Forces the dropdown open — useful for debugging styles
          * @default false
         */
        "defaultOpen"?: boolean;
        /**
          * Disables the component
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message
         */
        "error"?: string;
        /**
          * Hint text
         */
        "hint"?: string;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Name attribute for form submission
         */
        "name"?: string;
        /**
          * Emitted when focus leaves the component
         */
        "onCapBlur"?: (event: CapTagInputCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the tag list changes
         */
        "onCapChange"?: (event: CapTagInputCustomEvent<string[]>) => void;
        /**
          * Emitted when the input is focused
         */
        "onCapFocus"?: (event: CapTagInputCustomEvent<FocusEvent>) => void;
        /**
          * Emitted on every keystroke
         */
        "onCapInput"?: (event: CapTagInputCustomEvent<string>) => void;
        /**
          * Optional list of suggestions shown as an autocomplete dropdown while typing. If omitted, the component operates as a pure free-text tag input.
          * @default []
         */
        "options"?: TagInputOption[];
        /**
          * Placeholder shown when input is empty and no tags are present
         */
        "placeholder"?: string;
        /**
          * Marks the component as required
          * @default false
         */
        "required"?: boolean;
        /**
          * Current tags. When a suggestion is selected, stores the option's value. When typed freely, stores the raw text.
          * @default []
         */
        "value"?: string[];
    }
    interface CapTextarea {
        /**
          * Accessible label for when no visible label is used
         */
        "ariaLabel"?: string;
        /**
          * Disables the textarea
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message — takes priority over hint and success
         */
        "error"?: string;
        /**
          * Hint text shown below the textarea
         */
        "hint"?: string;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Maximum number of characters allowed
         */
        "maxlength"?: number;
        /**
          * Name attribute for form submission
         */
        "name"?: string;
        /**
          * Emitted when the textarea loses focus
         */
        "onCapBlur"?: (event: CapTextareaCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the value changes (on blur)
         */
        "onCapChange"?: (event: CapTextareaCustomEvent<string>) => void;
        /**
          * Emitted when the textarea is focused
         */
        "onCapFocus"?: (event: CapTextareaCustomEvent<FocusEvent>) => void;
        /**
          * Emitted on every keystroke
         */
        "onCapInput"?: (event: CapTextareaCustomEvent<string>) => void;
        /**
          * Placeholder text
         */
        "placeholder"?: string;
        /**
          * Makes the textarea read-only
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Marks the textarea as required
          * @default false
         */
        "required"?: boolean;
        /**
          * Whether the textarea can be resized
          * @default 'vertical'
         */
        "resize"?: TextareaResize;
        /**
          * Number of visible rows
          * @default 4
         */
        "rows"?: number;
        /**
          * Success message — takes priority over hint
         */
        "success"?: string;
        /**
          * The current value of the textarea
          * @default ''
         */
        "value"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }

    interface CapButtonAttributes {
        "variant": ButtonVariant;
        "size": ButtonSize;
        "type": ButtonType;
        "disabled": boolean;
        "loading": boolean;
        "fullWidth": boolean;
        "ariaLabel": string;
    }
    interface CapCheckboxAttributes {
        "checked": boolean;
        "indeterminate": boolean;
        "disabled": boolean;
        "required": boolean;
        "name": string;
        "value": string;
        "label": string;
        "hint": string;
        "error": string;
    }
    interface CapComboboxAttributes {
        "value": string;
        "placeholder": string;
        "name": string;
        "label": string;
        "hint": string;
        "error": string;
        "disabled": boolean;
        "required": boolean;
        "freeText": boolean;
        "defaultOpen": boolean;
    }
    interface CapDropdownMenuAttributes {
        "label": string;
        "icon": string;
        "align": 'start' | 'end';
        "disabled": boolean;
    }
    interface CapInputAttributes {
        "type": InputType;
        "value": string;
        "name": string;
        "placeholder": string;
        "label": string;
        "hint": string;
        "error": string;
        "success": string;
        "disabled": boolean;
        "readonly": boolean;
        "required": boolean;
    }
    interface CapMultiselectAttributes {
        "placeholder": string;
        "name": string;
        "label": string;
        "hint": string;
        "error": string;
        "disabled": boolean;
        "required": boolean;
        "overflow": MultiselectOverflow;
        "maxVisibleChips": number;
        "filterable": boolean;
        "defaultOpen": boolean;
    }
    interface CapRadioAttributes {
        "checked": boolean;
        "disabled": boolean;
        "required": boolean;
        "name": string;
        "value": string;
        "label": string;
        "hint": string;
        "error": string;
    }
    interface CapRadioGroupAttributes {
        "value": string;
        "name": string;
        "disabled": boolean;
        "required": boolean;
        "label": string;
        "hint": string;
        "error": string;
    }
    interface CapSelectAttributes {
        "value": string;
        "placeholder": string;
        "name": string;
        "label": string;
        "hint": string;
        "error": string;
        "disabled": boolean;
        "required": boolean;
    }
    interface CapTagInputAttributes {
        "placeholder": string;
        "name": string;
        "label": string;
        "hint": string;
        "error": string;
        "disabled": boolean;
        "required": boolean;
        "defaultOpen": boolean;
    }
    interface CapTextareaAttributes {
        "value": string;
        "name": string;
        "placeholder": string;
        "label": string;
        "hint": string;
        "error": string;
        "success": string;
        "rows": number;
        "resize": TextareaResize;
        "maxlength": number;
        "disabled": boolean;
        "readonly": boolean;
        "required": boolean;
        "ariaLabel": string;
    }
    interface MyComponentAttributes {
        "first": string;
        "middle": string;
        "last": string;
    }

    interface IntrinsicElements {
        "cap-button": Omit<CapButton, keyof CapButtonAttributes> & { [K in keyof CapButton & keyof CapButtonAttributes]?: CapButton[K] } & { [K in keyof CapButton & keyof CapButtonAttributes as `attr:${K}`]?: CapButtonAttributes[K] } & { [K in keyof CapButton & keyof CapButtonAttributes as `prop:${K}`]?: CapButton[K] };
        "cap-checkbox": Omit<CapCheckbox, keyof CapCheckboxAttributes> & { [K in keyof CapCheckbox & keyof CapCheckboxAttributes]?: CapCheckbox[K] } & { [K in keyof CapCheckbox & keyof CapCheckboxAttributes as `attr:${K}`]?: CapCheckboxAttributes[K] } & { [K in keyof CapCheckbox & keyof CapCheckboxAttributes as `prop:${K}`]?: CapCheckbox[K] };
        "cap-combobox": Omit<CapCombobox, keyof CapComboboxAttributes> & { [K in keyof CapCombobox & keyof CapComboboxAttributes]?: CapCombobox[K] } & { [K in keyof CapCombobox & keyof CapComboboxAttributes as `attr:${K}`]?: CapComboboxAttributes[K] } & { [K in keyof CapCombobox & keyof CapComboboxAttributes as `prop:${K}`]?: CapCombobox[K] };
        "cap-dropdown-menu": Omit<CapDropdownMenu, keyof CapDropdownMenuAttributes> & { [K in keyof CapDropdownMenu & keyof CapDropdownMenuAttributes]?: CapDropdownMenu[K] } & { [K in keyof CapDropdownMenu & keyof CapDropdownMenuAttributes as `attr:${K}`]?: CapDropdownMenuAttributes[K] } & { [K in keyof CapDropdownMenu & keyof CapDropdownMenuAttributes as `prop:${K}`]?: CapDropdownMenu[K] };
        "cap-input": Omit<CapInput, keyof CapInputAttributes> & { [K in keyof CapInput & keyof CapInputAttributes]?: CapInput[K] } & { [K in keyof CapInput & keyof CapInputAttributes as `attr:${K}`]?: CapInputAttributes[K] } & { [K in keyof CapInput & keyof CapInputAttributes as `prop:${K}`]?: CapInput[K] };
        "cap-multiselect": Omit<CapMultiselect, keyof CapMultiselectAttributes> & { [K in keyof CapMultiselect & keyof CapMultiselectAttributes]?: CapMultiselect[K] } & { [K in keyof CapMultiselect & keyof CapMultiselectAttributes as `attr:${K}`]?: CapMultiselectAttributes[K] } & { [K in keyof CapMultiselect & keyof CapMultiselectAttributes as `prop:${K}`]?: CapMultiselect[K] };
        "cap-radio": Omit<CapRadio, keyof CapRadioAttributes> & { [K in keyof CapRadio & keyof CapRadioAttributes]?: CapRadio[K] } & { [K in keyof CapRadio & keyof CapRadioAttributes as `attr:${K}`]?: CapRadioAttributes[K] } & { [K in keyof CapRadio & keyof CapRadioAttributes as `prop:${K}`]?: CapRadio[K] };
        "cap-radio-group": Omit<CapRadioGroup, keyof CapRadioGroupAttributes> & { [K in keyof CapRadioGroup & keyof CapRadioGroupAttributes]?: CapRadioGroup[K] } & { [K in keyof CapRadioGroup & keyof CapRadioGroupAttributes as `attr:${K}`]?: CapRadioGroupAttributes[K] } & { [K in keyof CapRadioGroup & keyof CapRadioGroupAttributes as `prop:${K}`]?: CapRadioGroup[K] };
        "cap-select": Omit<CapSelect, keyof CapSelectAttributes> & { [K in keyof CapSelect & keyof CapSelectAttributes]?: CapSelect[K] } & { [K in keyof CapSelect & keyof CapSelectAttributes as `attr:${K}`]?: CapSelectAttributes[K] } & { [K in keyof CapSelect & keyof CapSelectAttributes as `prop:${K}`]?: CapSelect[K] };
        "cap-tag-input": Omit<CapTagInput, keyof CapTagInputAttributes> & { [K in keyof CapTagInput & keyof CapTagInputAttributes]?: CapTagInput[K] } & { [K in keyof CapTagInput & keyof CapTagInputAttributes as `attr:${K}`]?: CapTagInputAttributes[K] } & { [K in keyof CapTagInput & keyof CapTagInputAttributes as `prop:${K}`]?: CapTagInput[K] };
        "cap-textarea": Omit<CapTextarea, keyof CapTextareaAttributes> & { [K in keyof CapTextarea & keyof CapTextareaAttributes]?: CapTextarea[K] } & { [K in keyof CapTextarea & keyof CapTextareaAttributes as `attr:${K}`]?: CapTextareaAttributes[K] } & { [K in keyof CapTextarea & keyof CapTextareaAttributes as `prop:${K}`]?: CapTextarea[K] };
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cap-button": LocalJSX.IntrinsicElements["cap-button"] & JSXBase.HTMLAttributes<HTMLCapButtonElement>;
            "cap-checkbox": LocalJSX.IntrinsicElements["cap-checkbox"] & JSXBase.HTMLAttributes<HTMLCapCheckboxElement>;
            "cap-combobox": LocalJSX.IntrinsicElements["cap-combobox"] & JSXBase.HTMLAttributes<HTMLCapComboboxElement>;
            "cap-dropdown-menu": LocalJSX.IntrinsicElements["cap-dropdown-menu"] & JSXBase.HTMLAttributes<HTMLCapDropdownMenuElement>;
            "cap-input": LocalJSX.IntrinsicElements["cap-input"] & JSXBase.HTMLAttributes<HTMLCapInputElement>;
            "cap-multiselect": LocalJSX.IntrinsicElements["cap-multiselect"] & JSXBase.HTMLAttributes<HTMLCapMultiselectElement>;
            "cap-radio": LocalJSX.IntrinsicElements["cap-radio"] & JSXBase.HTMLAttributes<HTMLCapRadioElement>;
            "cap-radio-group": LocalJSX.IntrinsicElements["cap-radio-group"] & JSXBase.HTMLAttributes<HTMLCapRadioGroupElement>;
            "cap-select": LocalJSX.IntrinsicElements["cap-select"] & JSXBase.HTMLAttributes<HTMLCapSelectElement>;
            "cap-tag-input": LocalJSX.IntrinsicElements["cap-tag-input"] & JSXBase.HTMLAttributes<HTMLCapTagInputElement>;
            "cap-textarea": LocalJSX.IntrinsicElements["cap-textarea"] & JSXBase.HTMLAttributes<HTMLCapTextareaElement>;
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
