/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AccordionItem } from "./components/cap-accordion/cap-accordion";
import { AlertVariant } from "./components/cap-alert/cap-alert";
import { BadgeSize, BadgeVariant } from "./components/cap-badge/cap-badge";
import { ButtonSize, ButtonType, ButtonVariant } from "./components/cap-button/cap-button";
import { ComboboxOption } from "./components/cap-combobox/cap-combobox";
import { MenuItem } from "./components/cap-dropdown-menu/cap-dropdown-menu";
import { MenuItem as MenuItem1 } from "./components/cap-dropdown-menu/cap-dropdown-menu";
import { InputType } from "./components/cap-input/cap-input";
import { MultiselectOption, MultiselectOverflow } from "./components/cap-multiselect/cap-multiselect";
import { ProgressVariant } from "./components/cap-progress/cap-progress";
import { SelectOption } from "./components/cap-select/cap-select";
import { SpinnerSize, SpinnerVariant } from "./components/cap-spinner/cap-spinner";
import { TabItem } from "./components/cap-tabs/cap-tabs";
import { TagInputOption } from "./components/cap-tag-input/cap-tag-input";
import { TextareaResize } from "./components/cap-textarea/cap-textarea";
import { ToastOptions, ToastPosition } from "./components/cap-toast/cap-toast";
export { AccordionItem } from "./components/cap-accordion/cap-accordion";
export { AlertVariant } from "./components/cap-alert/cap-alert";
export { BadgeSize, BadgeVariant } from "./components/cap-badge/cap-badge";
export { ButtonSize, ButtonType, ButtonVariant } from "./components/cap-button/cap-button";
export { ComboboxOption } from "./components/cap-combobox/cap-combobox";
export { MenuItem } from "./components/cap-dropdown-menu/cap-dropdown-menu";
export { MenuItem as MenuItem1 } from "./components/cap-dropdown-menu/cap-dropdown-menu";
export { InputType } from "./components/cap-input/cap-input";
export { MultiselectOption, MultiselectOverflow } from "./components/cap-multiselect/cap-multiselect";
export { ProgressVariant } from "./components/cap-progress/cap-progress";
export { SelectOption } from "./components/cap-select/cap-select";
export { SpinnerSize, SpinnerVariant } from "./components/cap-spinner/cap-spinner";
export { TabItem } from "./components/cap-tabs/cap-tabs";
export { TagInputOption } from "./components/cap-tag-input/cap-tag-input";
export { TextareaResize } from "./components/cap-textarea/cap-textarea";
export { ToastOptions, ToastPosition } from "./components/cap-toast/cap-toast";
export namespace Components {
    interface CapAccordion {
        /**
          * Items to render
          * @default []
         */
        "items": AccordionItem[];
        /**
          * Allow multiple panels to be open simultaneously
          * @default false
         */
        "multiple": boolean;
        /**
          * ID(s) of the open panel(s). Pass a string for single mode, or an array for multiple mode. When unset the accordion starts collapsed.
          * @default []
         */
        "openItems": string | string[];
    }
    interface CapAlert {
        /**
          * Show a dismiss (×) button
          * @default false
         */
        "dismissible": boolean;
        /**
          * Bold title line above the message
          * @default ''
         */
        "heading": string;
        /**
          * Visual style
          * @default 'default'
         */
        "variant": AlertVariant;
    }
    interface CapBadge {
        /**
          * Size of the badge
          * @default 'md'
         */
        "size": BadgeSize;
        /**
          * Visual style variant
          * @default 'default'
         */
        "variant": BadgeVariant;
    }
    interface CapButton {
        /**
          * Accessible label for icon-only buttons
         */
        "ariaLabel": string;
        /**
          * Disables the button
          * @default false
         */
        "disabled": boolean;
        /**
          * Stretches the button to full container width
          * @default false
         */
        "fullWidth": boolean;
        /**
          * Shows a loading spinner and disables interaction
          * @default false
         */
        "loading": boolean;
        /**
          * Size of the button
          * @default 'md'
         */
        "size": ButtonSize;
        /**
          * HTML button type
          * @default 'button'
         */
        "type": ButtonType;
        /**
          * Visual style of the button
          * @default 'primary'
         */
        "variant": ButtonVariant;
    }
    interface CapCheckbox {
        /**
          * Whether the checkbox is checked
          * @default false
         */
        "checked": boolean;
        /**
          * Disables the checkbox
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message
         */
        "error": string;
        /**
          * Hint text
         */
        "hint": string;
        /**
          * Indeterminate state — visually a dash, neither checked nor unchecked
          * @default false
         */
        "indeterminate": boolean;
        /**
          * Label text
         */
        "label": string;
        /**
          * Name attribute for form submission
         */
        "name": string;
        /**
          * Marks the checkbox as required
          * @default false
         */
        "required": boolean;
        /**
          * Value submitted with the form
         */
        "value": string;
    }
    interface CapCombobox {
        /**
          * Forces the dropdown open — useful for debugging styles
          * @default false
         */
        "defaultOpen": boolean;
        /**
          * Disables the combobox
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message
         */
        "error": string;
        /**
          * When true, typed text that doesn't match any option is accepted as a valid value. When false (default), blurring without selecting reverts the input to the last valid selection.
          * @default false
         */
        "freeText": boolean;
        /**
          * Hint text
         */
        "hint": string;
        /**
          * Label text
         */
        "label": string;
        /**
          * Name attribute for form submission
         */
        "name": string;
        /**
          * Array of options to filter and display
          * @default []
         */
        "options": ComboboxOption[];
        /**
          * Placeholder shown when input is empty
         */
        "placeholder": string;
        /**
          * Marks the combobox as required
          * @default false
         */
        "required": boolean;
        /**
          * Committed value — option.value when selected, or typed text when freeText=true
          * @default ''
         */
        "value": string;
    }
    interface CapContextMenu {
        /**
          * Disables the context menu (browser default is shown instead)
          * @default false
         */
        "disabled": boolean;
        /**
          * Menu items
          * @default []
         */
        "items": MenuItem[];
        /**
          * Accessible label for the menu panel
          * @default 'Context menu'
         */
        "label": string;
    }
    interface CapDropdownMenu {
        /**
          * Horizontal alignment of the menu panel relative to the trigger
          * @default 'start'
         */
        "align": 'start' | 'end';
        /**
          * Disables the trigger
          * @default false
         */
        "disabled": boolean;
        /**
          * Optional icon shown in the trigger
         */
        "icon": string;
        /**
          * Menu items
          * @default []
         */
        "items": MenuItem1[];
        /**
          * Trigger button label
          * @default ''
         */
        "label": string;
    }
    interface CapInput {
        /**
          * Disables the input
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message — takes priority over hint and success
         */
        "error": string;
        /**
          * Hint text
         */
        "hint": string;
        /**
          * Label text
         */
        "label": string;
        /**
          * Input name for forms
         */
        "name": string;
        /**
          * Placeholder text
         */
        "placeholder": string;
        /**
          * Makes the input read-only
          * @default false
         */
        "readonly": boolean;
        /**
          * Marks the input as required
          * @default false
         */
        "required": boolean;
        /**
          * Success message — takes priority over hint
         */
        "success": string;
        /**
          * Input type
          * @default 'text'
         */
        "type": InputType;
        /**
          * Input value
          * @default ''
         */
        "value": string;
    }
    interface CapModal {
        /**
          * Close the modal when the backdrop is clicked. Set to false to require explicit close action.
          * @default true
         */
        "closeOnBackdrop": boolean;
        /**
          * Modal title shown in the header
          * @default ''
         */
        "heading": string;
        /**
          * Programmatically close the modal
         */
        "hide": () => Promise<void>;
        /**
          * Hide the default close (×) button in the header
          * @default false
         */
        "hideClose": boolean;
        /**
          * Whether the modal is open
          * @default false
         */
        "open": boolean;
        /**
          * Programmatically open the modal
         */
        "show": () => Promise<void>;
        /**
          * Width of the modal panel. Any valid CSS width value, e.g. '480px', '60vw', '100%'.
          * @default '480px'
         */
        "width": string;
    }
    interface CapMultiselect {
        /**
          * Forces the dropdown open — useful for debugging styles
          * @default false
         */
        "defaultOpen": boolean;
        /**
          * Disables the component
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message
         */
        "error": string;
        /**
          * When true, a text input is shown inside the trigger for filtering options. When false (default), the trigger is a select-only control.
          * @default false
         */
        "filterable": boolean;
        /**
          * Hint text
         */
        "hint": string;
        /**
          * Label text
         */
        "label": string;
        /**
          * Maximum chips shown in the trigger before a "+N" badge appears. Only relevant when overflow="single-line".
          * @default 3
         */
        "maxVisibleChips": number;
        /**
          * Name attribute for form submission
         */
        "name": string;
        /**
          * Array of options to display
          * @default []
         */
        "options": MultiselectOption[];
        /**
          * Controls chip layout. grow (default): the trigger expands vertically as chips are added. single-line: trigger stays one line; excess chips collapse into a "+N" badge.
          * @default 'grow'
         */
        "overflow": MultiselectOverflow;
        /**
          * Placeholder shown when no value is selected
         */
        "placeholder": string;
        /**
          * Marks the component as required
          * @default false
         */
        "required": boolean;
        /**
          * Currently selected values
          * @default []
         */
        "value": string[];
    }
    interface CapProgress {
        /**
          * Accessible label
          * @default ''
         */
        "label": string;
        /**
          * Maximum value (default 100)
          * @default 100
         */
        "max": number;
        /**
          * Show the numeric percentage next to the bar
          * @default false
         */
        "showValue": boolean;
        /**
          * Current value. When undefined the bar shows an indeterminate animation.
          * @default undefined
         */
        "value": number | undefined;
        /**
          * Color variant
          * @default 'default'
         */
        "variant": ProgressVariant;
    }
    interface CapRadio {
        /**
          * Whether this radio is selected
          * @default false
         */
        "checked": boolean;
        /**
          * Disables the radio
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message
         */
        "error": string;
        /**
          * Hint text
         */
        "hint": string;
        /**
          * Label text
         */
        "label": string;
        /**
          * Name attribute — shared across radios in the same group
         */
        "name": string;
        /**
          * Marks the radio as required
          * @default false
         */
        "required": boolean;
        /**
          * Value submitted with the form
         */
        "value": string;
    }
    interface CapRadioGroup {
        /**
          * Disables all child radios
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message
         */
        "error": string;
        /**
          * Hint text
         */
        "hint": string;
        /**
          * Group label
         */
        "label": string;
        /**
          * Name shared across all child cap-radio elements
         */
        "name": string;
        /**
          * Marks all child radios as required
          * @default false
         */
        "required": boolean;
        /**
          * Currently selected value
         */
        "value": string;
    }
    interface CapSelect {
        /**
          * Disables the select
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message
         */
        "error": string;
        /**
          * Hint text
         */
        "hint": string;
        /**
          * Label text
         */
        "label": string;
        /**
          * Name attribute for form submission
         */
        "name": string;
        /**
          * Array of options to render
          * @default []
         */
        "options": SelectOption[];
        /**
          * Placeholder shown when no value is selected
         */
        "placeholder": string;
        /**
          * Marks the select as required
          * @default false
         */
        "required": boolean;
        /**
          * Currently selected value
          * @default ''
         */
        "value": string;
    }
    interface CapSpinner {
        /**
          * Accessible label announced to screen readers
          * @default 'Loading…'
         */
        "label": string;
        /**
          * Size of the spinner
          * @default 'md'
         */
        "size": SpinnerSize;
        /**
          * Visual animation style
          * @default 'circle'
         */
        "variant": SpinnerVariant;
    }
    interface CapSwitch {
        /**
          * Whether the switch is on
          * @default false
         */
        "checked": boolean;
        /**
          * Disables the switch
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message displayed below the switch
         */
        "error": string;
        /**
          * Hint text displayed below the switch
         */
        "hint": string;
        /**
          * Label text displayed above the switch
         */
        "label": string;
        /**
          * Name attribute for form submission
         */
        "name": string;
        /**
          * Marks the switch as required
          * @default false
         */
        "required": boolean;
        /**
          * Value submitted with the form when checked
          * @default 'on'
         */
        "value": string;
    }
    interface CapTabs {
        /**
          * ID of the active tab
          * @default ''
         */
        "activeTab": string;
        /**
          * Tab definitions
          * @default []
         */
        "tabs": TabItem[];
    }
    interface CapTagInput {
        /**
          * Forces the dropdown open — useful for debugging styles
          * @default false
         */
        "defaultOpen": boolean;
        /**
          * Disables the component
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message
         */
        "error": string;
        /**
          * Hint text
         */
        "hint": string;
        /**
          * Label text
         */
        "label": string;
        /**
          * Name attribute for form submission
         */
        "name": string;
        /**
          * Optional list of suggestions shown as an autocomplete dropdown while typing. If omitted, the component operates as a pure free-text tag input.
          * @default []
         */
        "options": TagInputOption[];
        /**
          * Placeholder shown when input is empty and no tags are present
         */
        "placeholder": string;
        /**
          * Marks the component as required
          * @default false
         */
        "required": boolean;
        /**
          * Current tags. When a suggestion is selected, stores the option's value. When typed freely, stores the raw text.
          * @default []
         */
        "value": string[];
    }
    interface CapTextarea {
        /**
          * Accessible label for when no visible label is used
         */
        "ariaLabel": string;
        /**
          * Disables the textarea
          * @default false
         */
        "disabled": boolean;
        /**
          * Error message — takes priority over hint and success
         */
        "error": string;
        /**
          * Hint text shown below the textarea
         */
        "hint": string;
        /**
          * Label text
         */
        "label": string;
        /**
          * Maximum number of characters allowed
         */
        "maxlength": number;
        /**
          * Name attribute for form submission
         */
        "name": string;
        /**
          * Placeholder text
         */
        "placeholder": string;
        /**
          * Makes the textarea read-only
          * @default false
         */
        "readonly": boolean;
        /**
          * Marks the textarea as required
          * @default false
         */
        "required": boolean;
        /**
          * Whether the textarea can be resized
          * @default 'vertical'
         */
        "resize": TextareaResize;
        /**
          * Number of visible rows
          * @default 4
         */
        "rows": number;
        /**
          * Success message — takes priority over hint
         */
        "success": string;
        /**
          * The current value of the textarea
          * @default ''
         */
        "value": string;
    }
    interface CapToast {
        /**
          * Remove all toasts immediately
         */
        "clear": () => Promise<void>;
        /**
          * Default auto-dismiss duration in ms (0 = no auto-dismiss)
          * @default 4000
         */
        "defaultDuration": number;
        /**
          * Remove a toast by id (with exit animation)
         */
        "dismiss": (id: string) => Promise<void>;
        /**
          * Where toasts stack on screen
          * @default 'top-right'
         */
        "position": ToastPosition;
        /**
          * Add a toast notification. Returns the id so you can dismiss it programmatically.
         */
        "show": (options: ToastOptions) => Promise<string>;
    }
    interface CapTooltip {
        /**
          * Tooltip text content
          * @default ''
         */
        "content": string;
        /**
          * Delay in milliseconds before showing the tooltip
          * @default 150
         */
        "delay": number;
        /**
          * Disables the tooltip
          * @default false
         */
        "disabled": boolean;
        /**
          * Preferred placement of the tooltip relative to the trigger
          * @default 'top'
         */
        "placement": 'top' | 'bottom' | 'left' | 'right';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface CapAccordionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapAccordionElement;
}
export interface CapAlertCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapAlertElement;
}
export interface CapButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapButtonElement;
}
export interface CapCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapCheckboxElement;
}
export interface CapComboboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapComboboxElement;
}
export interface CapContextMenuCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapContextMenuElement;
}
export interface CapDropdownMenuCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapDropdownMenuElement;
}
export interface CapInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapInputElement;
}
export interface CapModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapModalElement;
}
export interface CapMultiselectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapMultiselectElement;
}
export interface CapRadioCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapRadioElement;
}
export interface CapRadioGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapRadioGroupElement;
}
export interface CapSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapSelectElement;
}
export interface CapSwitchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapSwitchElement;
}
export interface CapTabsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapTabsElement;
}
export interface CapTagInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapTagInputElement;
}
export interface CapTextareaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapTextareaElement;
}
export interface CapToastCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCapToastElement;
}
declare global {
    interface HTMLCapAccordionElementEventMap {
        "capChange": { id: string; open: boolean; openItems: string[] };
    }
    interface HTMLCapAccordionElement extends Components.CapAccordion, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapAccordionElementEventMap>(type: K, listener: (this: HTMLCapAccordionElement, ev: CapAccordionCustomEvent<HTMLCapAccordionElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapAccordionElementEventMap>(type: K, listener: (this: HTMLCapAccordionElement, ev: CapAccordionCustomEvent<HTMLCapAccordionElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapAccordionElement: {
        prototype: HTMLCapAccordionElement;
        new (): HTMLCapAccordionElement;
    };
    interface HTMLCapAlertElementEventMap {
        "capDismiss": void;
    }
    interface HTMLCapAlertElement extends Components.CapAlert, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapAlertElementEventMap>(type: K, listener: (this: HTMLCapAlertElement, ev: CapAlertCustomEvent<HTMLCapAlertElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapAlertElementEventMap>(type: K, listener: (this: HTMLCapAlertElement, ev: CapAlertCustomEvent<HTMLCapAlertElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapAlertElement: {
        prototype: HTMLCapAlertElement;
        new (): HTMLCapAlertElement;
    };
    interface HTMLCapBadgeElement extends Components.CapBadge, HTMLStencilElement {
    }
    var HTMLCapBadgeElement: {
        prototype: HTMLCapBadgeElement;
        new (): HTMLCapBadgeElement;
    };
    interface HTMLCapButtonElementEventMap {
        "capClick": MouseEvent;
    }
    interface HTMLCapButtonElement extends Components.CapButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapButtonElementEventMap>(type: K, listener: (this: HTMLCapButtonElement, ev: CapButtonCustomEvent<HTMLCapButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapButtonElementEventMap>(type: K, listener: (this: HTMLCapButtonElement, ev: CapButtonCustomEvent<HTMLCapButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapButtonElement: {
        prototype: HTMLCapButtonElement;
        new (): HTMLCapButtonElement;
    };
    interface HTMLCapCheckboxElementEventMap {
        "capChange": boolean;
    }
    interface HTMLCapCheckboxElement extends Components.CapCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapCheckboxElementEventMap>(type: K, listener: (this: HTMLCapCheckboxElement, ev: CapCheckboxCustomEvent<HTMLCapCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapCheckboxElementEventMap>(type: K, listener: (this: HTMLCapCheckboxElement, ev: CapCheckboxCustomEvent<HTMLCapCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapCheckboxElement: {
        prototype: HTMLCapCheckboxElement;
        new (): HTMLCapCheckboxElement;
    };
    interface HTMLCapComboboxElementEventMap {
        "capChange": string;
        "capInput": string;
        "capFocus": FocusEvent;
        "capBlur": FocusEvent;
    }
    interface HTMLCapComboboxElement extends Components.CapCombobox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapComboboxElementEventMap>(type: K, listener: (this: HTMLCapComboboxElement, ev: CapComboboxCustomEvent<HTMLCapComboboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapComboboxElementEventMap>(type: K, listener: (this: HTMLCapComboboxElement, ev: CapComboboxCustomEvent<HTMLCapComboboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapComboboxElement: {
        prototype: HTMLCapComboboxElement;
        new (): HTMLCapComboboxElement;
    };
    interface HTMLCapContextMenuElementEventMap {
        "capSelect": MenuItem;
        "capToggle": { item: MenuItem; checked: boolean };
    }
    interface HTMLCapContextMenuElement extends Components.CapContextMenu, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapContextMenuElementEventMap>(type: K, listener: (this: HTMLCapContextMenuElement, ev: CapContextMenuCustomEvent<HTMLCapContextMenuElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapContextMenuElementEventMap>(type: K, listener: (this: HTMLCapContextMenuElement, ev: CapContextMenuCustomEvent<HTMLCapContextMenuElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapContextMenuElement: {
        prototype: HTMLCapContextMenuElement;
        new (): HTMLCapContextMenuElement;
    };
    interface HTMLCapDropdownMenuElementEventMap {
        "capSelect": MenuItem1;
        "capToggle": { item: MenuItem1; checked: boolean };
    }
    interface HTMLCapDropdownMenuElement extends Components.CapDropdownMenu, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapDropdownMenuElementEventMap>(type: K, listener: (this: HTMLCapDropdownMenuElement, ev: CapDropdownMenuCustomEvent<HTMLCapDropdownMenuElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapDropdownMenuElementEventMap>(type: K, listener: (this: HTMLCapDropdownMenuElement, ev: CapDropdownMenuCustomEvent<HTMLCapDropdownMenuElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapDropdownMenuElement: {
        prototype: HTMLCapDropdownMenuElement;
        new (): HTMLCapDropdownMenuElement;
    };
    interface HTMLCapInputElementEventMap {
        "capChange": string;
        "capInput": string;
        "capFocus": FocusEvent;
        "capBlur": FocusEvent;
        "capClear": void;
    }
    interface HTMLCapInputElement extends Components.CapInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapInputElementEventMap>(type: K, listener: (this: HTMLCapInputElement, ev: CapInputCustomEvent<HTMLCapInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapInputElementEventMap>(type: K, listener: (this: HTMLCapInputElement, ev: CapInputCustomEvent<HTMLCapInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapInputElement: {
        prototype: HTMLCapInputElement;
        new (): HTMLCapInputElement;
    };
    interface HTMLCapModalElementEventMap {
        "capClose": void;
        "capOpen": void;
    }
    interface HTMLCapModalElement extends Components.CapModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapModalElementEventMap>(type: K, listener: (this: HTMLCapModalElement, ev: CapModalCustomEvent<HTMLCapModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapModalElementEventMap>(type: K, listener: (this: HTMLCapModalElement, ev: CapModalCustomEvent<HTMLCapModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapModalElement: {
        prototype: HTMLCapModalElement;
        new (): HTMLCapModalElement;
    };
    interface HTMLCapMultiselectElementEventMap {
        "capChange": string[];
        "capInput": string;
        "capFocus": FocusEvent;
        "capBlur": FocusEvent;
    }
    interface HTMLCapMultiselectElement extends Components.CapMultiselect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapMultiselectElementEventMap>(type: K, listener: (this: HTMLCapMultiselectElement, ev: CapMultiselectCustomEvent<HTMLCapMultiselectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapMultiselectElementEventMap>(type: K, listener: (this: HTMLCapMultiselectElement, ev: CapMultiselectCustomEvent<HTMLCapMultiselectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapMultiselectElement: {
        prototype: HTMLCapMultiselectElement;
        new (): HTMLCapMultiselectElement;
    };
    interface HTMLCapProgressElement extends Components.CapProgress, HTMLStencilElement {
    }
    var HTMLCapProgressElement: {
        prototype: HTMLCapProgressElement;
        new (): HTMLCapProgressElement;
    };
    interface HTMLCapRadioElementEventMap {
        "capChange": string;
    }
    interface HTMLCapRadioElement extends Components.CapRadio, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapRadioElementEventMap>(type: K, listener: (this: HTMLCapRadioElement, ev: CapRadioCustomEvent<HTMLCapRadioElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapRadioElementEventMap>(type: K, listener: (this: HTMLCapRadioElement, ev: CapRadioCustomEvent<HTMLCapRadioElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapRadioElement: {
        prototype: HTMLCapRadioElement;
        new (): HTMLCapRadioElement;
    };
    interface HTMLCapRadioGroupElementEventMap {
        "capChange": string;
    }
    interface HTMLCapRadioGroupElement extends Components.CapRadioGroup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapRadioGroupElementEventMap>(type: K, listener: (this: HTMLCapRadioGroupElement, ev: CapRadioGroupCustomEvent<HTMLCapRadioGroupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapRadioGroupElementEventMap>(type: K, listener: (this: HTMLCapRadioGroupElement, ev: CapRadioGroupCustomEvent<HTMLCapRadioGroupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapRadioGroupElement: {
        prototype: HTMLCapRadioGroupElement;
        new (): HTMLCapRadioGroupElement;
    };
    interface HTMLCapSelectElementEventMap {
        "capChange": string;
        "capFocus": FocusEvent;
        "capBlur": FocusEvent;
    }
    interface HTMLCapSelectElement extends Components.CapSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapSelectElementEventMap>(type: K, listener: (this: HTMLCapSelectElement, ev: CapSelectCustomEvent<HTMLCapSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapSelectElementEventMap>(type: K, listener: (this: HTMLCapSelectElement, ev: CapSelectCustomEvent<HTMLCapSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapSelectElement: {
        prototype: HTMLCapSelectElement;
        new (): HTMLCapSelectElement;
    };
    interface HTMLCapSpinnerElement extends Components.CapSpinner, HTMLStencilElement {
    }
    var HTMLCapSpinnerElement: {
        prototype: HTMLCapSpinnerElement;
        new (): HTMLCapSpinnerElement;
    };
    interface HTMLCapSwitchElementEventMap {
        "capChange": { checked: boolean; value: string };
        "capFocus": void;
        "capBlur": void;
    }
    interface HTMLCapSwitchElement extends Components.CapSwitch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapSwitchElementEventMap>(type: K, listener: (this: HTMLCapSwitchElement, ev: CapSwitchCustomEvent<HTMLCapSwitchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapSwitchElementEventMap>(type: K, listener: (this: HTMLCapSwitchElement, ev: CapSwitchCustomEvent<HTMLCapSwitchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapSwitchElement: {
        prototype: HTMLCapSwitchElement;
        new (): HTMLCapSwitchElement;
    };
    interface HTMLCapTabsElementEventMap {
        "capChange": { id: string };
    }
    interface HTMLCapTabsElement extends Components.CapTabs, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapTabsElementEventMap>(type: K, listener: (this: HTMLCapTabsElement, ev: CapTabsCustomEvent<HTMLCapTabsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapTabsElementEventMap>(type: K, listener: (this: HTMLCapTabsElement, ev: CapTabsCustomEvent<HTMLCapTabsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapTabsElement: {
        prototype: HTMLCapTabsElement;
        new (): HTMLCapTabsElement;
    };
    interface HTMLCapTagInputElementEventMap {
        "capChange": string[];
        "capInput": string;
        "capFocus": FocusEvent;
        "capBlur": FocusEvent;
    }
    interface HTMLCapTagInputElement extends Components.CapTagInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapTagInputElementEventMap>(type: K, listener: (this: HTMLCapTagInputElement, ev: CapTagInputCustomEvent<HTMLCapTagInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapTagInputElementEventMap>(type: K, listener: (this: HTMLCapTagInputElement, ev: CapTagInputCustomEvent<HTMLCapTagInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapTagInputElement: {
        prototype: HTMLCapTagInputElement;
        new (): HTMLCapTagInputElement;
    };
    interface HTMLCapTextareaElementEventMap {
        "capChange": string;
        "capInput": string;
        "capFocus": FocusEvent;
        "capBlur": FocusEvent;
    }
    interface HTMLCapTextareaElement extends Components.CapTextarea, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapTextareaElementEventMap>(type: K, listener: (this: HTMLCapTextareaElement, ev: CapTextareaCustomEvent<HTMLCapTextareaElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapTextareaElementEventMap>(type: K, listener: (this: HTMLCapTextareaElement, ev: CapTextareaCustomEvent<HTMLCapTextareaElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapTextareaElement: {
        prototype: HTMLCapTextareaElement;
        new (): HTMLCapTextareaElement;
    };
    interface HTMLCapToastElementEventMap {
        "capDismiss": { id: string };
    }
    interface HTMLCapToastElement extends Components.CapToast, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCapToastElementEventMap>(type: K, listener: (this: HTMLCapToastElement, ev: CapToastCustomEvent<HTMLCapToastElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCapToastElementEventMap>(type: K, listener: (this: HTMLCapToastElement, ev: CapToastCustomEvent<HTMLCapToastElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCapToastElement: {
        prototype: HTMLCapToastElement;
        new (): HTMLCapToastElement;
    };
    interface HTMLCapTooltipElement extends Components.CapTooltip, HTMLStencilElement {
    }
    var HTMLCapTooltipElement: {
        prototype: HTMLCapTooltipElement;
        new (): HTMLCapTooltipElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cap-accordion": HTMLCapAccordionElement;
        "cap-alert": HTMLCapAlertElement;
        "cap-badge": HTMLCapBadgeElement;
        "cap-button": HTMLCapButtonElement;
        "cap-checkbox": HTMLCapCheckboxElement;
        "cap-combobox": HTMLCapComboboxElement;
        "cap-context-menu": HTMLCapContextMenuElement;
        "cap-dropdown-menu": HTMLCapDropdownMenuElement;
        "cap-input": HTMLCapInputElement;
        "cap-modal": HTMLCapModalElement;
        "cap-multiselect": HTMLCapMultiselectElement;
        "cap-progress": HTMLCapProgressElement;
        "cap-radio": HTMLCapRadioElement;
        "cap-radio-group": HTMLCapRadioGroupElement;
        "cap-select": HTMLCapSelectElement;
        "cap-spinner": HTMLCapSpinnerElement;
        "cap-switch": HTMLCapSwitchElement;
        "cap-tabs": HTMLCapTabsElement;
        "cap-tag-input": HTMLCapTagInputElement;
        "cap-textarea": HTMLCapTextareaElement;
        "cap-toast": HTMLCapToastElement;
        "cap-tooltip": HTMLCapTooltipElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CapAccordion {
        /**
          * Items to render
          * @default []
         */
        "items"?: AccordionItem[];
        /**
          * Allow multiple panels to be open simultaneously
          * @default false
         */
        "multiple"?: boolean;
        /**
          * Emitted when a panel is toggled. Detail: `{ id, open, openItems }`
         */
        "onCapChange"?: (event: CapAccordionCustomEvent<{ id: string; open: boolean; openItems: string[] }>) => void;
        /**
          * ID(s) of the open panel(s). Pass a string for single mode, or an array for multiple mode. When unset the accordion starts collapsed.
          * @default []
         */
        "openItems"?: string | string[];
    }
    interface CapAlert {
        /**
          * Show a dismiss (×) button
          * @default false
         */
        "dismissible"?: boolean;
        /**
          * Bold title line above the message
          * @default ''
         */
        "heading"?: string;
        /**
          * Emitted when the dismiss button is clicked
         */
        "onCapDismiss"?: (event: CapAlertCustomEvent<void>) => void;
        /**
          * Visual style
          * @default 'default'
         */
        "variant"?: AlertVariant;
    }
    interface CapBadge {
        /**
          * Size of the badge
          * @default 'md'
         */
        "size"?: BadgeSize;
        /**
          * Visual style variant
          * @default 'default'
         */
        "variant"?: BadgeVariant;
    }
    interface CapButton {
        /**
          * Accessible label for icon-only buttons
         */
        "ariaLabel"?: string;
        /**
          * Disables the button
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Stretches the button to full container width
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * Shows a loading spinner and disables interaction
          * @default false
         */
        "loading"?: boolean;
        /**
          * Emitted when the button is clicked
         */
        "onCapClick"?: (event: CapButtonCustomEvent<MouseEvent>) => void;
        /**
          * Size of the button
          * @default 'md'
         */
        "size"?: ButtonSize;
        /**
          * HTML button type
          * @default 'button'
         */
        "type"?: ButtonType;
        /**
          * Visual style of the button
          * @default 'primary'
         */
        "variant"?: ButtonVariant;
    }
    interface CapCheckbox {
        /**
          * Whether the checkbox is checked
          * @default false
         */
        "checked"?: boolean;
        /**
          * Disables the checkbox
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message
         */
        "error"?: string;
        /**
          * Hint text
         */
        "hint"?: string;
        /**
          * Indeterminate state — visually a dash, neither checked nor unchecked
          * @default false
         */
        "indeterminate"?: boolean;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Name attribute for form submission
         */
        "name"?: string;
        /**
          * Emitted when the checked state changes
         */
        "onCapChange"?: (event: CapCheckboxCustomEvent<boolean>) => void;
        /**
          * Marks the checkbox as required
          * @default false
         */
        "required"?: boolean;
        /**
          * Value submitted with the form
         */
        "value"?: string;
    }
    interface CapCombobox {
        /**
          * Forces the dropdown open — useful for debugging styles
          * @default false
         */
        "defaultOpen"?: boolean;
        /**
          * Disables the combobox
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message
         */
        "error"?: string;
        /**
          * When true, typed text that doesn't match any option is accepted as a valid value. When false (default), blurring without selecting reverts the input to the last valid selection.
          * @default false
         */
        "freeText"?: boolean;
        /**
          * Hint text
         */
        "hint"?: string;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Name attribute for form submission
         */
        "name"?: string;
        /**
          * Emitted when focus leaves the component
         */
        "onCapBlur"?: (event: CapComboboxCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the committed value changes
         */
        "onCapChange"?: (event: CapComboboxCustomEvent<string>) => void;
        /**
          * Emitted when the input is focused
         */
        "onCapFocus"?: (event: CapComboboxCustomEvent<FocusEvent>) => void;
        /**
          * Emitted on every keystroke
         */
        "onCapInput"?: (event: CapComboboxCustomEvent<string>) => void;
        /**
          * Array of options to filter and display
          * @default []
         */
        "options"?: ComboboxOption[];
        /**
          * Placeholder shown when input is empty
         */
        "placeholder"?: string;
        /**
          * Marks the combobox as required
          * @default false
         */
        "required"?: boolean;
        /**
          * Committed value — option.value when selected, or typed text when freeText=true
          * @default ''
         */
        "value"?: string;
    }
    interface CapContextMenu {
        /**
          * Disables the context menu (browser default is shown instead)
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Menu items
          * @default []
         */
        "items"?: MenuItem[];
        /**
          * Accessible label for the menu panel
          * @default 'Context menu'
         */
        "label"?: string;
        /**
          * Emitted when an action or link item is activated
         */
        "onCapSelect"?: (event: CapContextMenuCustomEvent<MenuItem>) => void;
        /**
          * Emitted when a toggle item is activated; checked reflects the new state
         */
        "onCapToggle"?: (event: CapContextMenuCustomEvent<{ item: MenuItem; checked: boolean }>) => void;
    }
    interface CapDropdownMenu {
        /**
          * Horizontal alignment of the menu panel relative to the trigger
          * @default 'start'
         */
        "align"?: 'start' | 'end';
        /**
          * Disables the trigger
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Optional icon shown in the trigger
         */
        "icon"?: string;
        /**
          * Menu items
          * @default []
         */
        "items"?: MenuItem1[];
        /**
          * Trigger button label
          * @default ''
         */
        "label"?: string;
        /**
          * Emitted when an action or link item is activated
         */
        "onCapSelect"?: (event: CapDropdownMenuCustomEvent<MenuItem1>) => void;
        /**
          * Emitted when a toggle item is activated; checked reflects the new state
         */
        "onCapToggle"?: (event: CapDropdownMenuCustomEvent<{ item: MenuItem1; checked: boolean }>) => void;
    }
    interface CapInput {
        /**
          * Disables the input
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message — takes priority over hint and success
         */
        "error"?: string;
        /**
          * Hint text
         */
        "hint"?: string;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Input name for forms
         */
        "name"?: string;
        /**
          * Emitted when the input loses focus
         */
        "onCapBlur"?: (event: CapInputCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the value changes
         */
        "onCapChange"?: (event: CapInputCustomEvent<string>) => void;
        /**
          * Emitted when the clear button is clicked (search type)
         */
        "onCapClear"?: (event: CapInputCustomEvent<void>) => void;
        /**
          * Emitted when the input is focused
         */
        "onCapFocus"?: (event: CapInputCustomEvent<FocusEvent>) => void;
        /**
          * Emitted on input (every keystroke)
         */
        "onCapInput"?: (event: CapInputCustomEvent<string>) => void;
        /**
          * Placeholder text
         */
        "placeholder"?: string;
        /**
          * Makes the input read-only
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Marks the input as required
          * @default false
         */
        "required"?: boolean;
        /**
          * Success message — takes priority over hint
         */
        "success"?: string;
        /**
          * Input type
          * @default 'text'
         */
        "type"?: InputType;
        /**
          * Input value
          * @default ''
         */
        "value"?: string;
    }
    interface CapModal {
        /**
          * Close the modal when the backdrop is clicked. Set to false to require explicit close action.
          * @default true
         */
        "closeOnBackdrop"?: boolean;
        /**
          * Modal title shown in the header
          * @default ''
         */
        "heading"?: string;
        /**
          * Hide the default close (×) button in the header
          * @default false
         */
        "hideClose"?: boolean;
        /**
          * Emitted when the modal requests to close (× button, Escape, or backdrop click)
         */
        "onCapClose"?: (event: CapModalCustomEvent<void>) => void;
        /**
          * Emitted after the modal finishes opening
         */
        "onCapOpen"?: (event: CapModalCustomEvent<void>) => void;
        /**
          * Whether the modal is open
          * @default false
         */
        "open"?: boolean;
        /**
          * Width of the modal panel. Any valid CSS width value, e.g. '480px', '60vw', '100%'.
          * @default '480px'
         */
        "width"?: string;
    }
    interface CapMultiselect {
        /**
          * Forces the dropdown open — useful for debugging styles
          * @default false
         */
        "defaultOpen"?: boolean;
        /**
          * Disables the component
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message
         */
        "error"?: string;
        /**
          * When true, a text input is shown inside the trigger for filtering options. When false (default), the trigger is a select-only control.
          * @default false
         */
        "filterable"?: boolean;
        /**
          * Hint text
         */
        "hint"?: string;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Maximum chips shown in the trigger before a "+N" badge appears. Only relevant when overflow="single-line".
          * @default 3
         */
        "maxVisibleChips"?: number;
        /**
          * Name attribute for form submission
         */
        "name"?: string;
        /**
          * Emitted when focus leaves the component
         */
        "onCapBlur"?: (event: CapMultiselectCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the selected values change
         */
        "onCapChange"?: (event: CapMultiselectCustomEvent<string[]>) => void;
        /**
          * Emitted when the trigger is focused
         */
        "onCapFocus"?: (event: CapMultiselectCustomEvent<FocusEvent>) => void;
        /**
          * Emitted on every keystroke in filterable mode
         */
        "onCapInput"?: (event: CapMultiselectCustomEvent<string>) => void;
        /**
          * Array of options to display
          * @default []
         */
        "options"?: MultiselectOption[];
        /**
          * Controls chip layout. grow (default): the trigger expands vertically as chips are added. single-line: trigger stays one line; excess chips collapse into a "+N" badge.
          * @default 'grow'
         */
        "overflow"?: MultiselectOverflow;
        /**
          * Placeholder shown when no value is selected
         */
        "placeholder"?: string;
        /**
          * Marks the component as required
          * @default false
         */
        "required"?: boolean;
        /**
          * Currently selected values
          * @default []
         */
        "value"?: string[];
    }
    interface CapProgress {
        /**
          * Accessible label
          * @default ''
         */
        "label"?: string;
        /**
          * Maximum value (default 100)
          * @default 100
         */
        "max"?: number;
        /**
          * Show the numeric percentage next to the bar
          * @default false
         */
        "showValue"?: boolean;
        /**
          * Current value. When undefined the bar shows an indeterminate animation.
          * @default undefined
         */
        "value"?: number | undefined;
        /**
          * Color variant
          * @default 'default'
         */
        "variant"?: ProgressVariant;
    }
    interface CapRadio {
        /**
          * Whether this radio is selected
          * @default false
         */
        "checked"?: boolean;
        /**
          * Disables the radio
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message
         */
        "error"?: string;
        /**
          * Hint text
         */
        "hint"?: string;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Name attribute — shared across radios in the same group
         */
        "name"?: string;
        /**
          * Emitted when this radio is selected
         */
        "onCapChange"?: (event: CapRadioCustomEvent<string>) => void;
        /**
          * Marks the radio as required
          * @default false
         */
        "required"?: boolean;
        /**
          * Value submitted with the form
         */
        "value"?: string;
    }
    interface CapRadioGroup {
        /**
          * Disables all child radios
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message
         */
        "error"?: string;
        /**
          * Hint text
         */
        "hint"?: string;
        /**
          * Group label
         */
        "label"?: string;
        /**
          * Name shared across all child cap-radio elements
         */
        "name"?: string;
        /**
          * Emitted when the selected value changes
         */
        "onCapChange"?: (event: CapRadioGroupCustomEvent<string>) => void;
        /**
          * Marks all child radios as required
          * @default false
         */
        "required"?: boolean;
        /**
          * Currently selected value
         */
        "value"?: string;
    }
    interface CapSelect {
        /**
          * Disables the select
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message
         */
        "error"?: string;
        /**
          * Hint text
         */
        "hint"?: string;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Name attribute for form submission
         */
        "name"?: string;
        /**
          * Emitted when focus leaves the component
         */
        "onCapBlur"?: (event: CapSelectCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the selected value changes
         */
        "onCapChange"?: (event: CapSelectCustomEvent<string>) => void;
        /**
          * Emitted when the trigger is focused
         */
        "onCapFocus"?: (event: CapSelectCustomEvent<FocusEvent>) => void;
        /**
          * Array of options to render
          * @default []
         */
        "options"?: SelectOption[];
        /**
          * Placeholder shown when no value is selected
         */
        "placeholder"?: string;
        /**
          * Marks the select as required
          * @default false
         */
        "required"?: boolean;
        /**
          * Currently selected value
          * @default ''
         */
        "value"?: string;
    }
    interface CapSpinner {
        /**
          * Accessible label announced to screen readers
          * @default 'Loading…'
         */
        "label"?: string;
        /**
          * Size of the spinner
          * @default 'md'
         */
        "size"?: SpinnerSize;
        /**
          * Visual animation style
          * @default 'circle'
         */
        "variant"?: SpinnerVariant;
    }
    interface CapSwitch {
        /**
          * Whether the switch is on
          * @default false
         */
        "checked"?: boolean;
        /**
          * Disables the switch
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message displayed below the switch
         */
        "error"?: string;
        /**
          * Hint text displayed below the switch
         */
        "hint"?: string;
        /**
          * Label text displayed above the switch
         */
        "label"?: string;
        /**
          * Name attribute for form submission
         */
        "name"?: string;
        /**
          * Emitted when the switch loses focus
         */
        "onCapBlur"?: (event: CapSwitchCustomEvent<void>) => void;
        /**
          * Emitted when the checked state changes
         */
        "onCapChange"?: (event: CapSwitchCustomEvent<{ checked: boolean; value: string }>) => void;
        /**
          * Emitted when the switch receives focus
         */
        "onCapFocus"?: (event: CapSwitchCustomEvent<void>) => void;
        /**
          * Marks the switch as required
          * @default false
         */
        "required"?: boolean;
        /**
          * Value submitted with the form when checked
          * @default 'on'
         */
        "value"?: string;
    }
    interface CapTabs {
        /**
          * ID of the active tab
          * @default ''
         */
        "activeTab"?: string;
        /**
          * Emitted when the active tab changes. Detail: `{ id }` — the newly active tab id.
         */
        "onCapChange"?: (event: CapTabsCustomEvent<{ id: string }>) => void;
        /**
          * Tab definitions
          * @default []
         */
        "tabs"?: TabItem[];
    }
    interface CapTagInput {
        /**
          * Forces the dropdown open — useful for debugging styles
          * @default false
         */
        "defaultOpen"?: boolean;
        /**
          * Disables the component
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message
         */
        "error"?: string;
        /**
          * Hint text
         */
        "hint"?: string;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Name attribute for form submission
         */
        "name"?: string;
        /**
          * Emitted when focus leaves the component
         */
        "onCapBlur"?: (event: CapTagInputCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the tag list changes
         */
        "onCapChange"?: (event: CapTagInputCustomEvent<string[]>) => void;
        /**
          * Emitted when the input is focused
         */
        "onCapFocus"?: (event: CapTagInputCustomEvent<FocusEvent>) => void;
        /**
          * Emitted on every keystroke
         */
        "onCapInput"?: (event: CapTagInputCustomEvent<string>) => void;
        /**
          * Optional list of suggestions shown as an autocomplete dropdown while typing. If omitted, the component operates as a pure free-text tag input.
          * @default []
         */
        "options"?: TagInputOption[];
        /**
          * Placeholder shown when input is empty and no tags are present
         */
        "placeholder"?: string;
        /**
          * Marks the component as required
          * @default false
         */
        "required"?: boolean;
        /**
          * Current tags. When a suggestion is selected, stores the option's value. When typed freely, stores the raw text.
          * @default []
         */
        "value"?: string[];
    }
    interface CapTextarea {
        /**
          * Accessible label for when no visible label is used
         */
        "ariaLabel"?: string;
        /**
          * Disables the textarea
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Error message — takes priority over hint and success
         */
        "error"?: string;
        /**
          * Hint text shown below the textarea
         */
        "hint"?: string;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Maximum number of characters allowed
         */
        "maxlength"?: number;
        /**
          * Name attribute for form submission
         */
        "name"?: string;
        /**
          * Emitted when the textarea loses focus
         */
        "onCapBlur"?: (event: CapTextareaCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when the value changes (on blur)
         */
        "onCapChange"?: (event: CapTextareaCustomEvent<string>) => void;
        /**
          * Emitted when the textarea is focused
         */
        "onCapFocus"?: (event: CapTextareaCustomEvent<FocusEvent>) => void;
        /**
          * Emitted on every keystroke
         */
        "onCapInput"?: (event: CapTextareaCustomEvent<string>) => void;
        /**
          * Placeholder text
         */
        "placeholder"?: string;
        /**
          * Makes the textarea read-only
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Marks the textarea as required
          * @default false
         */
        "required"?: boolean;
        /**
          * Whether the textarea can be resized
          * @default 'vertical'
         */
        "resize"?: TextareaResize;
        /**
          * Number of visible rows
          * @default 4
         */
        "rows"?: number;
        /**
          * Success message — takes priority over hint
         */
        "success"?: string;
        /**
          * The current value of the textarea
          * @default ''
         */
        "value"?: string;
    }
    interface CapToast {
        /**
          * Default auto-dismiss duration in ms (0 = no auto-dismiss)
          * @default 4000
         */
        "defaultDuration"?: number;
        /**
          * Emitted when a toast is removed
         */
        "onCapDismiss"?: (event: CapToastCustomEvent<{ id: string }>) => void;
        /**
          * Where toasts stack on screen
          * @default 'top-right'
         */
        "position"?: ToastPosition;
    }
    interface CapTooltip {
        /**
          * Tooltip text content
          * @default ''
         */
        "content"?: string;
        /**
          * Delay in milliseconds before showing the tooltip
          * @default 150
         */
        "delay"?: number;
        /**
          * Disables the tooltip
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Preferred placement of the tooltip relative to the trigger
          * @default 'top'
         */
        "placement"?: 'top' | 'bottom' | 'left' | 'right';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }

    interface CapAccordionAttributes {
        "openItems": string | string[];
        "multiple": boolean;
    }
    interface CapAlertAttributes {
        "variant": AlertVariant;
        "heading": string;
        "dismissible": boolean;
    }
    interface CapBadgeAttributes {
        "variant": BadgeVariant;
        "size": BadgeSize;
    }
    interface CapButtonAttributes {
        "variant": ButtonVariant;
        "size": ButtonSize;
        "type": ButtonType;
        "disabled": boolean;
        "loading": boolean;
        "fullWidth": boolean;
        "ariaLabel": string;
    }
    interface CapCheckboxAttributes {
        "checked": boolean;
        "indeterminate": boolean;
        "disabled": boolean;
        "required": boolean;
        "name": string;
        "value": string;
        "label": string;
        "hint": string;
        "error": string;
    }
    interface CapComboboxAttributes {
        "value": string;
        "placeholder": string;
        "name": string;
        "label": string;
        "hint": string;
        "error": string;
        "disabled": boolean;
        "required": boolean;
        "freeText": boolean;
        "defaultOpen": boolean;
    }
    interface CapContextMenuAttributes {
        "label": string;
        "disabled": boolean;
    }
    interface CapDropdownMenuAttributes {
        "label": string;
        "icon": string;
        "align": 'start' | 'end';
        "disabled": boolean;
    }
    interface CapInputAttributes {
        "type": InputType;
        "value": string;
        "name": string;
        "placeholder": string;
        "label": string;
        "hint": string;
        "error": string;
        "success": string;
        "disabled": boolean;
        "readonly": boolean;
        "required": boolean;
    }
    interface CapModalAttributes {
        "open": boolean;
        "heading": string;
        "width": string;
        "hideClose": boolean;
        "closeOnBackdrop": boolean;
    }
    interface CapMultiselectAttributes {
        "placeholder": string;
        "name": string;
        "label": string;
        "hint": string;
        "error": string;
        "disabled": boolean;
        "required": boolean;
        "overflow": MultiselectOverflow;
        "maxVisibleChips": number;
        "filterable": boolean;
        "defaultOpen": boolean;
    }
    interface CapProgressAttributes {
        "value": number | undefined;
        "max": number;
        "label": string;
        "showValue": boolean;
        "variant": ProgressVariant;
    }
    interface CapRadioAttributes {
        "checked": boolean;
        "disabled": boolean;
        "required": boolean;
        "name": string;
        "value": string;
        "label": string;
        "hint": string;
        "error": string;
    }
    interface CapRadioGroupAttributes {
        "value": string;
        "name": string;
        "disabled": boolean;
        "required": boolean;
        "label": string;
        "hint": string;
        "error": string;
    }
    interface CapSelectAttributes {
        "value": string;
        "placeholder": string;
        "name": string;
        "label": string;
        "hint": string;
        "error": string;
        "disabled": boolean;
        "required": boolean;
    }
    interface CapSpinnerAttributes {
        "variant": SpinnerVariant;
        "size": SpinnerSize;
        "label": string;
    }
    interface CapSwitchAttributes {
        "checked": boolean;
        "disabled": boolean;
        "label": string;
        "hint": string;
        "error": string;
        "name": string;
        "value": string;
        "required": boolean;
    }
    interface CapTabsAttributes {
        "activeTab": string;
    }
    interface CapTagInputAttributes {
        "placeholder": string;
        "name": string;
        "label": string;
        "hint": string;
        "error": string;
        "disabled": boolean;
        "required": boolean;
        "defaultOpen": boolean;
    }
    interface CapTextareaAttributes {
        "value": string;
        "name": string;
        "placeholder": string;
        "label": string;
        "hint": string;
        "error": string;
        "success": string;
        "rows": number;
        "resize": TextareaResize;
        "maxlength": number;
        "disabled": boolean;
        "readonly": boolean;
        "required": boolean;
        "ariaLabel": string;
    }
    interface CapToastAttributes {
        "position": ToastPosition;
        "defaultDuration": number;
    }
    interface CapTooltipAttributes {
        "content": string;
        "placement": 'top' | 'bottom' | 'left' | 'right';
        "delay": number;
        "disabled": boolean;
    }
    interface MyComponentAttributes {
        "first": string;
        "middle": string;
        "last": string;
    }

    interface IntrinsicElements {
        "cap-accordion": Omit<CapAccordion, keyof CapAccordionAttributes> & { [K in keyof CapAccordion & keyof CapAccordionAttributes]?: CapAccordion[K] } & { [K in keyof CapAccordion & keyof CapAccordionAttributes as `attr:${K}`]?: CapAccordionAttributes[K] } & { [K in keyof CapAccordion & keyof CapAccordionAttributes as `prop:${K}`]?: CapAccordion[K] };
        "cap-alert": Omit<CapAlert, keyof CapAlertAttributes> & { [K in keyof CapAlert & keyof CapAlertAttributes]?: CapAlert[K] } & { [K in keyof CapAlert & keyof CapAlertAttributes as `attr:${K}`]?: CapAlertAttributes[K] } & { [K in keyof CapAlert & keyof CapAlertAttributes as `prop:${K}`]?: CapAlert[K] };
        "cap-badge": Omit<CapBadge, keyof CapBadgeAttributes> & { [K in keyof CapBadge & keyof CapBadgeAttributes]?: CapBadge[K] } & { [K in keyof CapBadge & keyof CapBadgeAttributes as `attr:${K}`]?: CapBadgeAttributes[K] } & { [K in keyof CapBadge & keyof CapBadgeAttributes as `prop:${K}`]?: CapBadge[K] };
        "cap-button": Omit<CapButton, keyof CapButtonAttributes> & { [K in keyof CapButton & keyof CapButtonAttributes]?: CapButton[K] } & { [K in keyof CapButton & keyof CapButtonAttributes as `attr:${K}`]?: CapButtonAttributes[K] } & { [K in keyof CapButton & keyof CapButtonAttributes as `prop:${K}`]?: CapButton[K] };
        "cap-checkbox": Omit<CapCheckbox, keyof CapCheckboxAttributes> & { [K in keyof CapCheckbox & keyof CapCheckboxAttributes]?: CapCheckbox[K] } & { [K in keyof CapCheckbox & keyof CapCheckboxAttributes as `attr:${K}`]?: CapCheckboxAttributes[K] } & { [K in keyof CapCheckbox & keyof CapCheckboxAttributes as `prop:${K}`]?: CapCheckbox[K] };
        "cap-combobox": Omit<CapCombobox, keyof CapComboboxAttributes> & { [K in keyof CapCombobox & keyof CapComboboxAttributes]?: CapCombobox[K] } & { [K in keyof CapCombobox & keyof CapComboboxAttributes as `attr:${K}`]?: CapComboboxAttributes[K] } & { [K in keyof CapCombobox & keyof CapComboboxAttributes as `prop:${K}`]?: CapCombobox[K] };
        "cap-context-menu": Omit<CapContextMenu, keyof CapContextMenuAttributes> & { [K in keyof CapContextMenu & keyof CapContextMenuAttributes]?: CapContextMenu[K] } & { [K in keyof CapContextMenu & keyof CapContextMenuAttributes as `attr:${K}`]?: CapContextMenuAttributes[K] } & { [K in keyof CapContextMenu & keyof CapContextMenuAttributes as `prop:${K}`]?: CapContextMenu[K] };
        "cap-dropdown-menu": Omit<CapDropdownMenu, keyof CapDropdownMenuAttributes> & { [K in keyof CapDropdownMenu & keyof CapDropdownMenuAttributes]?: CapDropdownMenu[K] } & { [K in keyof CapDropdownMenu & keyof CapDropdownMenuAttributes as `attr:${K}`]?: CapDropdownMenuAttributes[K] } & { [K in keyof CapDropdownMenu & keyof CapDropdownMenuAttributes as `prop:${K}`]?: CapDropdownMenu[K] };
        "cap-input": Omit<CapInput, keyof CapInputAttributes> & { [K in keyof CapInput & keyof CapInputAttributes]?: CapInput[K] } & { [K in keyof CapInput & keyof CapInputAttributes as `attr:${K}`]?: CapInputAttributes[K] } & { [K in keyof CapInput & keyof CapInputAttributes as `prop:${K}`]?: CapInput[K] };
        "cap-modal": Omit<CapModal, keyof CapModalAttributes> & { [K in keyof CapModal & keyof CapModalAttributes]?: CapModal[K] } & { [K in keyof CapModal & keyof CapModalAttributes as `attr:${K}`]?: CapModalAttributes[K] } & { [K in keyof CapModal & keyof CapModalAttributes as `prop:${K}`]?: CapModal[K] };
        "cap-multiselect": Omit<CapMultiselect, keyof CapMultiselectAttributes> & { [K in keyof CapMultiselect & keyof CapMultiselectAttributes]?: CapMultiselect[K] } & { [K in keyof CapMultiselect & keyof CapMultiselectAttributes as `attr:${K}`]?: CapMultiselectAttributes[K] } & { [K in keyof CapMultiselect & keyof CapMultiselectAttributes as `prop:${K}`]?: CapMultiselect[K] };
        "cap-progress": Omit<CapProgress, keyof CapProgressAttributes> & { [K in keyof CapProgress & keyof CapProgressAttributes]?: CapProgress[K] } & { [K in keyof CapProgress & keyof CapProgressAttributes as `attr:${K}`]?: CapProgressAttributes[K] } & { [K in keyof CapProgress & keyof CapProgressAttributes as `prop:${K}`]?: CapProgress[K] };
        "cap-radio": Omit<CapRadio, keyof CapRadioAttributes> & { [K in keyof CapRadio & keyof CapRadioAttributes]?: CapRadio[K] } & { [K in keyof CapRadio & keyof CapRadioAttributes as `attr:${K}`]?: CapRadioAttributes[K] } & { [K in keyof CapRadio & keyof CapRadioAttributes as `prop:${K}`]?: CapRadio[K] };
        "cap-radio-group": Omit<CapRadioGroup, keyof CapRadioGroupAttributes> & { [K in keyof CapRadioGroup & keyof CapRadioGroupAttributes]?: CapRadioGroup[K] } & { [K in keyof CapRadioGroup & keyof CapRadioGroupAttributes as `attr:${K}`]?: CapRadioGroupAttributes[K] } & { [K in keyof CapRadioGroup & keyof CapRadioGroupAttributes as `prop:${K}`]?: CapRadioGroup[K] };
        "cap-select": Omit<CapSelect, keyof CapSelectAttributes> & { [K in keyof CapSelect & keyof CapSelectAttributes]?: CapSelect[K] } & { [K in keyof CapSelect & keyof CapSelectAttributes as `attr:${K}`]?: CapSelectAttributes[K] } & { [K in keyof CapSelect & keyof CapSelectAttributes as `prop:${K}`]?: CapSelect[K] };
        "cap-spinner": Omit<CapSpinner, keyof CapSpinnerAttributes> & { [K in keyof CapSpinner & keyof CapSpinnerAttributes]?: CapSpinner[K] } & { [K in keyof CapSpinner & keyof CapSpinnerAttributes as `attr:${K}`]?: CapSpinnerAttributes[K] } & { [K in keyof CapSpinner & keyof CapSpinnerAttributes as `prop:${K}`]?: CapSpinner[K] };
        "cap-switch": Omit<CapSwitch, keyof CapSwitchAttributes> & { [K in keyof CapSwitch & keyof CapSwitchAttributes]?: CapSwitch[K] } & { [K in keyof CapSwitch & keyof CapSwitchAttributes as `attr:${K}`]?: CapSwitchAttributes[K] } & { [K in keyof CapSwitch & keyof CapSwitchAttributes as `prop:${K}`]?: CapSwitch[K] };
        "cap-tabs": Omit<CapTabs, keyof CapTabsAttributes> & { [K in keyof CapTabs & keyof CapTabsAttributes]?: CapTabs[K] } & { [K in keyof CapTabs & keyof CapTabsAttributes as `attr:${K}`]?: CapTabsAttributes[K] } & { [K in keyof CapTabs & keyof CapTabsAttributes as `prop:${K}`]?: CapTabs[K] };
        "cap-tag-input": Omit<CapTagInput, keyof CapTagInputAttributes> & { [K in keyof CapTagInput & keyof CapTagInputAttributes]?: CapTagInput[K] } & { [K in keyof CapTagInput & keyof CapTagInputAttributes as `attr:${K}`]?: CapTagInputAttributes[K] } & { [K in keyof CapTagInput & keyof CapTagInputAttributes as `prop:${K}`]?: CapTagInput[K] };
        "cap-textarea": Omit<CapTextarea, keyof CapTextareaAttributes> & { [K in keyof CapTextarea & keyof CapTextareaAttributes]?: CapTextarea[K] } & { [K in keyof CapTextarea & keyof CapTextareaAttributes as `attr:${K}`]?: CapTextareaAttributes[K] } & { [K in keyof CapTextarea & keyof CapTextareaAttributes as `prop:${K}`]?: CapTextarea[K] };
        "cap-toast": Omit<CapToast, keyof CapToastAttributes> & { [K in keyof CapToast & keyof CapToastAttributes]?: CapToast[K] } & { [K in keyof CapToast & keyof CapToastAttributes as `attr:${K}`]?: CapToastAttributes[K] } & { [K in keyof CapToast & keyof CapToastAttributes as `prop:${K}`]?: CapToast[K] };
        "cap-tooltip": Omit<CapTooltip, keyof CapTooltipAttributes> & { [K in keyof CapTooltip & keyof CapTooltipAttributes]?: CapTooltip[K] } & { [K in keyof CapTooltip & keyof CapTooltipAttributes as `attr:${K}`]?: CapTooltipAttributes[K] } & { [K in keyof CapTooltip & keyof CapTooltipAttributes as `prop:${K}`]?: CapTooltip[K] };
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cap-accordion": LocalJSX.IntrinsicElements["cap-accordion"] & JSXBase.HTMLAttributes<HTMLCapAccordionElement>;
            "cap-alert": LocalJSX.IntrinsicElements["cap-alert"] & JSXBase.HTMLAttributes<HTMLCapAlertElement>;
            "cap-badge": LocalJSX.IntrinsicElements["cap-badge"] & JSXBase.HTMLAttributes<HTMLCapBadgeElement>;
            "cap-button": LocalJSX.IntrinsicElements["cap-button"] & JSXBase.HTMLAttributes<HTMLCapButtonElement>;
            "cap-checkbox": LocalJSX.IntrinsicElements["cap-checkbox"] & JSXBase.HTMLAttributes<HTMLCapCheckboxElement>;
            "cap-combobox": LocalJSX.IntrinsicElements["cap-combobox"] & JSXBase.HTMLAttributes<HTMLCapComboboxElement>;
            "cap-context-menu": LocalJSX.IntrinsicElements["cap-context-menu"] & JSXBase.HTMLAttributes<HTMLCapContextMenuElement>;
            "cap-dropdown-menu": LocalJSX.IntrinsicElements["cap-dropdown-menu"] & JSXBase.HTMLAttributes<HTMLCapDropdownMenuElement>;
            "cap-input": LocalJSX.IntrinsicElements["cap-input"] & JSXBase.HTMLAttributes<HTMLCapInputElement>;
            "cap-modal": LocalJSX.IntrinsicElements["cap-modal"] & JSXBase.HTMLAttributes<HTMLCapModalElement>;
            "cap-multiselect": LocalJSX.IntrinsicElements["cap-multiselect"] & JSXBase.HTMLAttributes<HTMLCapMultiselectElement>;
            "cap-progress": LocalJSX.IntrinsicElements["cap-progress"] & JSXBase.HTMLAttributes<HTMLCapProgressElement>;
            "cap-radio": LocalJSX.IntrinsicElements["cap-radio"] & JSXBase.HTMLAttributes<HTMLCapRadioElement>;
            "cap-radio-group": LocalJSX.IntrinsicElements["cap-radio-group"] & JSXBase.HTMLAttributes<HTMLCapRadioGroupElement>;
            "cap-select": LocalJSX.IntrinsicElements["cap-select"] & JSXBase.HTMLAttributes<HTMLCapSelectElement>;
            "cap-spinner": LocalJSX.IntrinsicElements["cap-spinner"] & JSXBase.HTMLAttributes<HTMLCapSpinnerElement>;
            "cap-switch": LocalJSX.IntrinsicElements["cap-switch"] & JSXBase.HTMLAttributes<HTMLCapSwitchElement>;
            "cap-tabs": LocalJSX.IntrinsicElements["cap-tabs"] & JSXBase.HTMLAttributes<HTMLCapTabsElement>;
            "cap-tag-input": LocalJSX.IntrinsicElements["cap-tag-input"] & JSXBase.HTMLAttributes<HTMLCapTagInputElement>;
            "cap-textarea": LocalJSX.IntrinsicElements["cap-textarea"] & JSXBase.HTMLAttributes<HTMLCapTextareaElement>;
            "cap-toast": LocalJSX.IntrinsicElements["cap-toast"] & JSXBase.HTMLAttributes<HTMLCapToastElement>;
            "cap-tooltip": LocalJSX.IntrinsicElements["cap-tooltip"] & JSXBase.HTMLAttributes<HTMLCapTooltipElement>;
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
